export interface Product {
  id: string
  name: string
  category: string
  price: number
  originalPrice?: number
  image: string
  images: string[]
  rating: number
  inStock: boolean
  description: string
  features: string[]
  specifications: Record<string, string>
  sizes?: string[]
  size?: string
  colors?: string[]
  color?: string
}

export const categories = [
  { id: "daily-essentials", name: "Daily Essentials", icon: "🏠" },
  { id: "mens-fashion", name: "Men's Fashion", icon: "👔" },
  { id: "womens-fashion", name: "Women's Fashion", icon: "👗" },
  { id: "outdoor-camping", name: "Outdoor & Camping", icon: "⛺" },
  { id: "sports-equipment", name: "Sports Equipment", icon: "🏋️" },
  { id: "creative-decor", name: "Creative Decor", icon: "🎨" },
]

export const products: Product[] = [
  // Daily Essentials (20 products)
  {
    id: "de-001",
    name: "Portable Cutlery Set with Case",
    category: "daily-essentials",
    price: 12.99,
    originalPrice: 19.99,
    image: "/gods/portable-stainless-steel-cutlery-c3.jpg",
    images: ["/gods/portable-stainless-steel-cutlery-c.jpg", "/gods/portable-stainless-steel-cutlery-c1.jpg", "/gods/portable-stainless-steel-cutlery-c2.jpg", "/gods/portable-stainless-steel-cutlery-c3.jpg", "/gods/portable-stainless-steel-cutlery-c4.jpg", "/gods/portable-stainless-steel-cutlery-c5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Environmentally friendly glass tableware set, perfect for travel, office use or outdoor dining.",
    features: [
      "Food-grade rubber",
      "Portable carrying case",
      "Dishwasher safe",
      "Includes fork, spoon, knife, chopsticks",
    ],
    specifications: { Material: "Glass, rubber", Weight: "180g", Size: "19cm x 6cm" },
  },
  {
    id: "de-002",
    name: "Silicone Food Storage Containers Set",
    category: "daily-essentials",
    price: 24.99,
    originalPrice: 34.99,
    image: "/gods/colorful-silicone-collapsible-food-storage-contain4.jpg",
    images: ["/gods/colorful-silicone-collapsible-food-storage-contain.jpg", "/gods/colorful-silicone-collapsible-food-storage-contain1.jpg", "/gods/colorful-silicone-collapsible-food-storage-contain2.jpg", "/gods/colorful-silicone-collapsible-food-storage-contain5.jpg", "/gods/colorful-silicone-collapsible-food-storage-contain3.jpg", "/gods/colorful-silicone-collapsible-food-storage-contain4.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Collapsible silicone containers that save space and keep food fresh.",
    features: ["BPA-free silicone", "Microwave & freezer safe", "Collapsible design", "Set of 4 sizes"],
    specifications: { Material: "Food-grade Silicone", Temperature: "-40°C to 230°C" },
  },
  {
    id: "de-003",
    name: "Multi-Function Space-Saving Hangers",
    category: "daily-essentials",
    price: 15.99,
    image: "/gods/modern-multi-layer-clothing-hangers-organizer.jpg",
    images: ["/gods/modern-multi-layer-clothing-hangers-organizer.jpg", "/gods/modern-multi-layer-clothing-hangers-organizer1.jpg", "/gods/modern-multi-layer-clothing-hangers-organizer2.jpg", "/gods/modern-multi-layer-clothing-hangers-organizer3.jpg", "/gods/modern-multi-layer-clothing-hangers-organizer4.jpg", "/gods/modern-multi-layer-clothing-hangers-organizer5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "5-in-1 hangers that maximize closet space and keep clothes organized.",
    features: ["Can hold multiple pieces of clothing", "Anti-slip design", "Durable material"],
    specifications: { Material: "ABS Plastic", Dimensions: "42cm x 18cm", "Load Capacity": "15kg" },
  },
  {
    id: "de-004",
    name: "Compressed Travel Towel Set",
    category: "daily-essentials",
    price: 9.99,
    image: "/gods/compressed-cotton-travel-towels-in-packaging.jpg",
    images: ["/gods/compressed-cotton-travel-towels-in-packaging.jpg", "/gods/compressed-cotton-travel-towels-in-packaging1.jpg", "/gods/compressed-cotton-travel-towels-in-packaging2.jpg", "/gods/compressed-cotton-travel-towels-in-packaging3.jpg", "/gods/compressed-cotton-travel-towels-in-packaging4.jpg", "/gods/compressed-cotton-travel-towels-in-packaging5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Portable towel, extremely soft, perfect for travel use.",
    features: ["100% cotton", "Expands to full size", "Quick-dry", "Pack of 10"],
    specifications: { Material: "100% Cotton", Package: 'Ten pieces per pack', Size: '15cm x 30cm' }
  },
  {
    id: "de-005",
    name: "Travel Organizer Bag Set",
    category: "daily-essentials",
    price: 18.99,
    originalPrice: 29.99,
    image: "/gods/travel-packing-cubes-organizer-set.jpg",
    images: ["/gods/travel-packing-cubes-organizer-set.jpg", "/gods/travel-packing-cubes-organizer-set3.jpg", "/gods/travel-packing-cubes-organizer-set2.jpg", "/gods/travel-packing-cubes-organizer-set1.jpg"],
    rating: 4.9,
        inStock: true,
    description: "Extra-large capacity leather luggage bag, capable of efficiently organizing luggage items.",
    features: ["Multiple colors", "Waterproof material", "Large capacity",  "Leather material"],
    specifications: { Material: "Leather", Colors: "Multiple options" },
    colors: ["Black", "White", "Pink", "Brown"],
  },
  {
    id: "de-006",
    name: "Mini Robot Vacuum Cleaner",
    category: "daily-essentials",
    price: 49.99,
    originalPrice: 79.99,
    image: "/gods/compact-robot-vacuum-cleaner-for-home.jpg",
    images: ["/gods/compact-robot-vacuum-cleaner-for-home.jpg", "/gods/compact-robot-vacuum-cleaner-for-home1.jpg", "/gods/compact-robot-vacuum-cleaner-for-home2.jpg", "/gods/compact-robot-vacuum-cleaner-for-home3.jpg", "/gods/compact-robot-vacuum-cleaner-for-home4.jpg", "/gods/compact-robot-vacuum-cleaner-for-home5.jpg"],
    rating: 4.4,
        inStock: true,
    description: "Portable automatic vacuum cleaner, suitable for daily cleaning.",
    features: ["Auto-charging", "Low noise", "Smart navigation", "HEPA filter"],
    specifications: { "Battery Life": "90 minutes", "Noise Level": "55dB", Diameter: "28cm" },
  },
  {
    id: "de-007",
    name: "Electric Milk Frother",
    category: "daily-essentials",
    price: 14.99,
    image: "/gods/handheld-electric-milk-frother-coffee-tool.jpg",
    images: ["/gods/handheld-electric-milk-frother-coffee-tool.jpg", "/gods/handheld-electric-milk-frother-coffee-tool1.jpg", "/gods/handheld-electric-milk-frother-coffee-tool2.jpg", "/gods/handheld-electric-milk-frother-coffee-tool3.jpg", "/gods/handheld-electric-milk-frother-coffee-tool4.jpg", "/gods/handheld-electric-milk-frother-coffee-tool5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Create café-quality foam at home in seconds.",
    features: ["USB rechargeable", "Stainless steel whisk", "Quiet operation", "Easy to clean"],
    specifications: { Power: "3W", "Battery Capacity": "800mAh", Material: "Stainless Steel" },
  },
  {
    id: "de-008",
    name: "Adjustable Laptop Stand",
    category: "daily-essentials",
    price: 22.99,
    image: "/gods/ergonomic-adjustable-aluminum-laptop-stand.jpg",
    images: ["/gods/ergonomic-adjustable-aluminum-laptop-stand.jpg", "/gods/ergonomic-adjustable-aluminum-laptop-stand1.jpg", "/gods/ergonomic-adjustable-aluminum-laptop-stand2.jpg", "/gods/ergonomic-adjustable-aluminum-laptop-stand3.jpg", "/gods/ergonomic-adjustable-aluminum-laptop-stand4.jpg", "/gods/ergonomic-adjustable-aluminum-laptop-stand5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Ergonomic stand improves posture and cooling.",
    features: ["6 height levels", "Aluminum alloy", "Foldable design", 'Supports up to 17" laptops'],
    specifications: { Material: "Aluminum Alloy", Weight: "850g", "Max Load": "10kg" },
  },
  {
    id: "de-009",
    name: "LED Desk Lamp with Wireless Charging",
    category: "daily-essentials",
    price: 34.99,
    originalPrice: 49.99,
    image: "/gods/modern-led-desk-lamp-with-wireless-phone-charging.jpg",
    images: ["/gods/modern-led-desk-lamp-with-wireless-phone-charging.jpg", "/gods/modern-led-desk-lamp-with-wireless-phone-charging1.jpg", "/gods/modern-led-desk-lamp-with-wireless-phone-charging2.jpg", "/gods/modern-led-desk-lamp-with-wireless-phone-charging3.jpg", "/gods/modern-led-desk-lamp-with-wireless-phone-charging4.jpg", "/gods/modern-led-desk-lamp-with-wireless-phone-charging.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Multi-functional lamp with phone charging and adjustable brightness.",
    features: ["Wireless charging pad", "3 color modes", "Touch control", "USB port"],
    colors: ["Black", "Gold", "White"],
    specifications: { Power: "15W", "Color Temperature": "3000K-6000K", "Charging Output": "10W" },
  },
  {
    id: "de-010",
    name: "Insulated Lunch Box",
    category: "daily-essentials",
    price: 16.99,
    image: "/gods/insulated-stainless-steel-lunch-box-container.jpg",
    images: ["/gods/insulated-stainless-steel-lunch-box-container.jpg", "/gods/insulated-stainless-steel-lunch-box-container1.jpg", "/gods/insulated-stainless-steel-lunch-box-container2.jpg", "/gods/insulated-stainless-steel-lunch-box-container3.jpg", "/gods/insulated-stainless-steel-lunch-box-container4.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Keep meals hot or cold for hours with this premium lunch box.",
    features: ["Double-wall insulation", "Leak-proof", "Stainless steel", "2 compartments"],
    specifications: { Capacity: "1.2L", Material: "Stainless Steel 304", Dimensions: "11cm x 11cm x 20cm" },
  },
  {
    id: "de-011",
    name: "Digital Kitchen Scale",
    category: "daily-essentials",
    price: 11.99,
    image: "/gods/digital-kitchen-food-scale-with-lcd-display.jpg",
    images: ["/gods/digital-kitchen-food-scale-with-lcd-display.jpg", "/gods/digital-kitchen-food-scale-with-lcd-display1.jpg", "/gods/digital-kitchen-food-scale-with-lcd-display2.jpg", "/gods/digital-kitchen-food-scale-with-lcd-display3.jpg", "/gods/digital-kitchen-food-scale-with-lcd-display4.jpg", "/gods/digital-kitchen-food-scale-with-lcd-display5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Precise measurements for cooking and baking.",
    features: ["0.1g precision", "Tare function", "LCD display", "Auto shut-off"],
    specifications: { Capacity: "5kg", Accuracy: "0.1g", Power: "2x AAA batteries" },
  },
  {
    id: "de-012",
    name: "Bamboo Drawer Organizers",
    category: "daily-essentials",
    price: 19.99,
    image: "/gods/bamboo-drawer-divider-organizer-set.jpg",
    images: ["/gods/bamboo-drawer-divider-organizer-set.jpg", "/gods/bamboo-drawer-divider-organizer-set1.jpg", "/gods/bamboo-drawer-divider-organizer-set2.jpg", "/gods/bamboo-drawer-divider-organizer-set5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Eco-friendly organizers for kitchen and office drawers.",
    features: ["Natural bamboo", "Adjustable dividers", "Easy to clean"],
    specifications: { Material: "Bamboo", Finish: "Natural" },
  },
  {
    id: "de-013",
    name: "Electric Wine Opener Set",
    category: "daily-essentials",
    price: 27.99,
    image: "/gods/automatic-electric-wine-bottle-opener-set.jpg",
    images: ["/gods/automatic-electric-wine-bottle-opener-set.jpg", "/gods/automatic-electric-wine-bottle-opener-set1.jpg", "/gods/automatic-electric-wine-bottle-opener-set2.jpg", "/gods/automatic-electric-wine-bottle-opener-set3.jpg", "/gods/automatic-electric-wine-bottle-opener-set4.jpg", "/gods/automatic-electric-wine-bottle-opener-set5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Open wine bottles effortlessly with this electric opener.",
    features: ["Opens 30+ bottles per charge", "Foil cutter included", "LED indicator", "Elegant design"],
    colors: ["Black", "Silver"],
    specifications: {
      Power: "Rechargeable battery",
      Material: "Stainless Steel",
      Includes: "Opener, foil cutter, pourer",
    },
  },
  {
    id: "de-014",
    name: "Magnetic Knife Holder",
    category: "daily-essentials",
    price: 13.99,
    image: "/gods/wall-mounted-magnetic-knife-holder-strip.jpg",
    images: ["/gods/wall-mounted-magnetic-knife-holder-strip.jpg", "/gods/wall-mounted-magnetic-knife-holder-strip1.jpg", "/gods/wall-mounted-magnetic-knife-holder-strip2.jpg", "/gods/wall-mounted-magnetic-knife-holder-strip3.jpg", "/gods/wall-mounted-magnetic-knife-holder-strip4.jpg", "/gods/wall-mounted-magnetic-knife-holder-strip5.jpg"],
    rating: 4.7,
        inStock: true,
    colors: ['Ash-gray', 'Black', 'White'],    
    description: "Space-saving magnetic strip for kitchen knives.",
    features: ["Strong magnets", "Easy installation", "Bamboo or stainless steel", "40cm length"],
    specifications: { Length: "40cm", Material: "Bamboo/Stainless Steel", "Mounting Type": "Wall-mounted" },
  },
  {
    id: "de-015",
    name: "Shower Caddy Organizer",
    category: "daily-essentials",
    price: 21.99,
    image: "/gods/rust-proof-shower-caddy-organizer-shelves.jpg",
    images: ["/gods/rust-proof-shower-caddy-organizer-shelves.jpg", "/gods/rust-proof-shower-caddy-organizer-shelves1.jpg", "/gods/rust-proof-shower-caddy-organizer-shelves2.jpg", "/gods/rust-proof-shower-caddy-organizer-shelves3.jpg", "/gods/rust-proof-shower-caddy-organizer-shelves4.jpg", "/gods/rust-proof-shower-caddy-organizer-shelves5.jpg"],
    rating: 4.5,
        inStock: true,
    colors: ['Black', 'White', "Brown", "Gray"],    
    description: "Rust-proof shower organizer with multiple shelves.",
    features: [ "Canvas material", "Can increase storage capacity", "Adjustable divider", "No need for drilling"],
    specifications: { Material: "Canvas", StoragePosition: "Adjustable", Shelf: "Adjustable" },
  },
  {
    id: "de-016",
    name: "Automatic Soap Dispenser",
    category: "daily-essentials",
    price: 17.99,
    image: "/gods/automatic-touchless-soap-dispenser.jpg",
    images: ["/gods/automatic-touchless-soap-dispenser.jpg", "/gods/automatic-touchless-soap-dispenser1.jpg", "/gods/automatic-touchless-soap-dispenser2.jpg", "/gods/automatic-touchless-soap-dispenser3.jpg", "/gods/automatic-touchless-soap-dispenser4.jpg", "/gods/automatic-touchless-soap-dispenser.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Touchless soap dispenser for hygiene and convenience.",
    features: ["Infrared sensor", "Adjustable volume", "Waterproof", "USB rechargeable"],
    specifications: { Capacity: "350ml", Power: "USB rechargeable", Material: "ABS Plastic" },
  },
  {
    id: "de-017",
    name: "Cable Management Box",
    category: "daily-essentials",
    price: 14.99,
    image: "/gods/cable-organizer-management-box.jpg",
    images: ["/gods/cable-organizer-management-box.jpg", "/gods/cable-organizer-management-box1.jpg", "/gods/cable-organizer-management-box2.jpg", "/gods/cable-organizer-management-box3.jpg", "/gods/cable-organizer-management-box4.jpg", "/gods/cable-organizer-management-box5.jpg"],
    rating: 4.4,
        inStock: true,
    description: "Hide and organize messy cables and power strips.",
    colors: ['Black', 'White'],
    features: ["Large capacity", "Heat dissipation holes", "Non-slip base", "Modern design"],
    specifications: { Dimensions: "32cm x 13cm x 13cm", Material: "ABS Plastic", Color: "White/Black" },
  },
  {
    id: "de-018",
    name: "Reusable Silicone Food Bags",
    category: "daily-essentials",
    price: 18.99,
    image: "/gods/reusable-silicone-food-storage-bags-set.jpg",
    images: ["/gods/reusable-silicone-food-storage-bags-set.jpg", "/gods/reusable-silicone-food-storage-bags-set1.jpg", "/gods/reusable-silicone-food-storage-bags-set2.jpg", "/gods/reusable-silicone-food-storage-bags-set3.jpg", "/gods/reusable-silicone-food-storage-bags-set4.jpg", "/gods/reusable-silicone-food-storage-bags-set5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Eco-friendly alternative to plastic bags.",
    features: ["Set of 6", "Leak-proof seal", "Microwave safe", "Easy to clean"],
    colors: ["Green", "White", "Croci", "Blue", "Purplish Red"],
    specifications: { Material: "Food-grade Silicone", Temperature: "-40°C to 230°C" },
  },
  {
    id: "de-019",
    name: "UV Phone Sanitizer Box",
    category: "daily-essentials",
    price: 29.99,
    originalPrice: 44.99,
    image: "/gods/uv-phone-sanitizer-wireless-charger-box.jpg",
    images: ["/gods/uv-phone-sanitizer-wireless-charger-box.jpg", "/gods/uv-phone-sanitizer-wireless-charger-box1.jpg", "/gods/uv-phone-sanitizer-wireless-charger-box2.jpg", "/gods/uv-phone-sanitizer-wireless-charger-box3.jpg", "/gods/uv-phone-sanitizer-wireless-charger-box4.jpg", "/gods/uv-phone-sanitizer-wireless-charger-box5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Sanitize your phone and small items with UV-C light.",
    features: ["UV-C sterilization", "Wireless charging", "Aromatherapy function", "5-minute cycle"],
    specifications: { Power: "10W", "UV Wavelength": "253.7nm", Compatibility: 'Phones up to 6.5"' },
  },
  {
    id: "de-020",
    name: "Collapsible Laundry Basket",
    category: "daily-essentials",
    price: 16.99,
    image: "/gods/collapsible-laundry-basket-hamper.jpg",
    images: ["/gods/collapsible-laundry-basket-hamper.jpg", "/gods/collapsible-laundry-basket-hamper1.jpg", "/gods/collapsible-laundry-basket-hamper2.jpg", "/gods/collapsible-laundry-basket-hamper3.jpg", "/gods/collapsible-laundry-basket-hamper4.jpg", "/gods/collapsible-laundry-basket-hamper5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Space-saving laundry basket that folds flat.",
    colors: ["Gray", "Green", "Yellow", "White"],
    features: ["Collapsible design", "Reinforced handles", "Waterproof lining", "Large capacity"],
    specifications: { Capacity: "60L", Material: "Oxford Fabric", Dimensions: "40cm x 30cm x 50cm" },
  },
  // Men's Fashion (20 products)
  {
    id: "mf-001",
    name: "Quick-Dry Performance Polo Shirt",
    category: "mens-fashion",
    price: 24.99,
    originalPrice: 39.99,
    image: "/gods/mens-quick-dry-performance-polo-shirt.jpg",
    images: ["/gods/mens-quick-dry-performance-polo-shirt.jpg", "/gods/mens-quick-dry-performance-polo-shirt1.jpg", "/gods/mens-quick-dry-performance-polo-shirt2.jpg", "/gods/mens-quick-dry-performance-polo-shirt3.jpg", "/gods/mens-quick-dry-performance-polo-shirt4.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Breathable polo perfect for sports and casual wear.",
    colors: ["Black", "Gray"],
    features: ["Moisture-wicking fabric", "UV protection", "Anti-odor technology", "Multiple colors"],
    specifications: { Material: "95% Polyester, 5% Spandex", Sizes: "S-2XL", Care: "Machine washable" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "mf-002",
    name: "Slim Fit Business Casual Pants",
    category: "mens-fashion",
    price: 34.99,
    originalPrice: 54.99,
    image: "/gods/mens-slim-fit-business-casual-pants.jpg",
    images: ["/gods/mens-slim-fit-business-casual-pants.jpg", "/gods/mens-slim-fit-business-casual-pants1.jpg", "/gods/mens-slim-fit-business-casual-pants2.jpg", "/gods/mens-slim-fit-business-casual-pants3.jpg", "/gods/mens-slim-fit-business-casual-pants4.jpg", "/gods/mens-slim-fit-business-casual-pants5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Versatile pants for office and casual occasions.",
    features: ["Stretch fabric", "Wrinkle-resistant", "4-way stretch", "Multiple pockets"],
    specifications: { Material: "68% Polyester, 29% Rayon, 3% Spandex",},
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "mf-003",
    name: "Lightweight Down Jacket",
    category: "mens-fashion",
    price: 59.99,
    originalPrice: 99.99,
    image: "/gods/mens-lightweight-packable-down-jacket.jpg",
    images: ["/gods/mens-lightweight-packable-down-jacket.jpg", "/gods/mens-lightweight-packable-down-jacket1.jpg", "/gods/mens-lightweight-packable-down-jacket2.jpg", "/gods/mens-lightweight-packable-down-jacket3.jpg", "/gods/mens-lightweight-packable-down-jacket4.jpg", "/gods/mens-lightweight-packable-down-jacket5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Packable down jacket for cold weather.",
    features: ["90% down fill", "Water-resistant", "Packable design", "Lightweight"],
    specifications: { Fill: "90% Duck Down", Weight: "350g", Sizes: "S-2XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Brown"],
  },
  {
    id: "mf-004",
    name: "Premium Cotton Dress Socks Set",
    category: "mens-fashion",
    price: 19.99,
    image: "/gods/mens-premium-cotton-dress-socks-set.jpg",
    images: ["/gods/mens-premium-cotton-dress-socks-set.jpg", "/gods/mens-premium-cotton-dress-socks-set1.jpg", "/gods/mens-premium-cotton-dress-socks-set2.jpg", "/gods/mens-premium-cotton-dress-socks-set3.jpg", "/gods/mens-premium-cotton-dress-socks-set4.jpg", "/gods/mens-premium-cotton-dress-socks-set5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Comfortable dress socks for business and formal wear.",
    features: ["Breathable cotton", "Reinforced heel and toe", "Set of 6 pairs", "Multiple patterns"],
    specifications: {
      Material: "80% Cotton, 15% Polyester, 5% Spandex",
      Sizes: "One size fits most",
      Package: "6 pairs",
    },
    colors: ["Black", "White", "Gray", "Brown", "Skin"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "mf-005",
    name: "Classic Denim Shirt",
    category: "mens-fashion",
    price: 29.99,
    image: "/gods/mens-classic-denim-button-down-shirt.jpg",
    images: ["/gods/mens-classic-denim-button-down-shirt.jpg", "/gods/mens-classic-denim-button-down-shirt2.jpg", "/gods/mens-classic-denim-button-down-shirt3.jpg", "/gods/mens-classic-denim-button-down-shirt4.jpg", "/gods/mens-classic-denim-button-down-shirt5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Timeless denim shirt for casual style.",
    colors: ["Dark Blue", "Light Blue"],
    features: ["100% cotton denim", "Button-down collar", "Chest pockets", "Regular fit"],
    specifications: { Material: "100% Cotton", Weight: "8oz denim", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "mf-006",
    name: "Athletic Performance Shorts",
    category: "mens-fashion",
    price: 22.99,
    image: "/gods/mens-athletic-performance-running-shorts.jpg",
    images: ["/gods/mens-athletic-performance-running-shorts.jpg", "/gods/mens-athletic-performance-running-shorts1.jpg", "/gods/mens-athletic-performance-running-shorts2.jpg", "/gods/mens-athletic-performance-running-shorts3.jpg", "/gods/mens-athletic-performance-running-shorts4.jpg", "/gods/mens-athletic-performance-running-shorts5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Comfortable shorts for workouts and running.",
    features: ["Quick-dry fabric", "Zippered pockets", "Elastic waistband", "Reflective details"],
    specifications: { Material: "100% Polyester", Inseam: "7 inches", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Gray", "White", "Brown", "Black", "Blue"],
  },
  {
    id: "mf-007",
    name: "Leather Belt with Automatic Buckle",
    category: "mens-fashion",
    price: 26.99,
    image: "/gods/mens-leather-belt-automatic-buckle.jpg",
    images: ["/gods/mens-leather-belt-automatic-buckle.jpg", "/gods/mens-leather-belt-automatic-buckle1.jpg", "/gods/mens-leather-belt-automatic-buckle2.jpg", "/gods/mens-leather-belt-automatic-buckle3.jpg", "/gods/mens-leather-belt-automatic-buckle4.jpg", "/gods/mens-leather-belt-automatic-buckle5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Premium leather belt with modern automatic buckle.",
    features: ["Genuine leather", "Automatic buckle", "Adjustable length", "Gift box included"],
    specifications: { Material: "Genuine Leather", Width: "3.5cm", Length: "Adjustable 110-130cm" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Brown", "Gray", "Red"]
  },
  {
    id: "mf-008",
    name: "Merino Wool Sweater",
    category: "mens-fashion",
    price: 44.99,
    originalPrice: 69.99,
    image: "/gods/mens-merino-wool-crew-neck-sweater.jpg",
    images: ["/gods/mens-merino-wool-crew-neck-sweater.jpg", "/gods/mens-merino-wool-crew-neck-sweater1.jpg", "/gods/mens-merino-wool-crew-neck-sweater2.jpg", "/gods/mens-merino-wool-crew-neck-sweater3.jpg", "/gods/mens-merino-wool-crew-neck-sweater4.jpg", "/gods/mens-merino-wool-crew-neck-sweater5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Soft merino wool sweater for layering.",
    features: ["100% merino wool", "Temperature regulating", "Odor-resistant", "Classic fit"],
    specifications: { Material: "100% Merino Wool", Weight: "Midweight", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "White", "Blue", "Green", "Yellow", "Pink", "Purple", "Brown"],
  },
  {
    id: "mf-009",
    name: "Stretch Jeans Slim Fit",
    category: "mens-fashion",
    price: 39.99,
    originalPrice: 59.99,
    image: "/gods/mens-stretch-slim-fit-jeans.jpg",
    images: ["/gods/mens-stretch-slim-fit-jeans.jpg", "/gods/mens-stretch-slim-fit-jeans1.jpg", "/gods/mens-stretch-slim-fit-jeans2.jpg", "/gods/mens-stretch-slim-fit-jeans3.jpg", "/gods/mens-stretch-slim-fit-jeans4.jpg", "/gods/mens-stretch-slim-fit-jeans5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Comfortable stretch jeans with modern fit.",
    features: ["Stretch denim", "Fade-resistant", "5-pocket design", "Multiple washes"],
    specifications: { Material: "79% Cotton, 20% Polyester, 1% Spandex", Fit: "Slim", Sizes: "28-40" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "mf-010",
    name: "Windbreaker Jacket",
    category: "mens-fashion",
    price: 42.99,
    image: "/gods/mens-windbreaker-jacket-lightweight.jpg",
    images: ["/gods/mens-windbreaker-jacket-lightweight.jpg", "/gods/mens-windbreaker-jacket-lightweight1.jpg", "/gods/mens-windbreaker-jacket-lightweight2.jpg", "/gods/mens-windbreaker-jacket-lightweight3.jpg", "/gods/mens-windbreaker-jacket-lightweight4.jpg", "/gods/mens-windbreaker-jacket-lightweight5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Lightweight jacket for wind and light rain protection.",
    features: ["Water-resistant", "Packable hood", "Zippered pockets", "Adjustable cuffs"],
    specifications: { Material: "100% Nylon", Weight: "280g", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Brown", "Purple"]
  },
  {
    id: "mf-011",
    name: "Oxford Dress Shirt",
    category: "mens-fashion",
    price: 32.99,
    image: "/gods/mens-oxford-dress-shirt-button-down.jpg",
    images: ["/gods/mens-oxford-dress-shirt-button-down.jpg", "/gods/mens-oxford-dress-shirt-button-down1.jpg", "/gods/mens-oxford-dress-shirt-button-down2.jpg", "/gods/mens-oxford-dress-shirt-button-down3.jpg", "/gods/mens-oxford-dress-shirt-button-down4.jpg", "/gods/mens-oxford-dress-shirt-button-down5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Classic oxford shirt for business and formal occasions.",
    features: ["100% cotton oxford", "Button-down collar", "Wrinkle-resistant", "Regular fit"],
    specifications: { Material: "100% Cotton", Weave: "Oxford", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Brown", "Black", "silver"]
  },
  {
    id: "mf-012",
    name: "Cargo Shorts with Multiple Pockets",
    category: "mens-fashion",
    price: 27.99,
    image: "/gods/mens-cargo-shorts-multiple-pockets.jpg",
    images: ["/gods/mens-cargo-shorts-multiple-pockets.jpg", "/gods/mens-cargo-shorts-multiple-pockets1.jpg", "/gods/mens-cargo-shorts-multiple-pockets2.jpg", "/gods/mens-cargo-shorts-multiple-pockets3.jpg", "/gods/mens-cargo-shorts-multiple-pockets4.jpg", "/gods/mens-cargo-shorts-multiple-pockets5.jpg"],
    rating: 4.4,
        inStock: true,
    description: "Functional cargo shorts for outdoor activities.",
    features: ["8 pockets", "Durable fabric", "Belt included", "Relaxed fit"],
    specifications: { Material: "100% Cotton", Inseam: "11 inches", Sizes: "xs-xxl" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Green", "Brown", "Purple"]
  },
  {
    id: "mf-013",
    name: "Thermal Base Layer Set",
    category: "mens-fashion",
    price: 34.99,
    image: "/gods/mens-thermal-base-layer-set.jpg",
    images: ["/gods/mens-thermal-base-layer-set.jpg", "/gods/mens-thermal-base-layer-set1.jpg", "/gods/mens-thermal-base-layer-set2.jpg", "/gods/mens-thermal-base-layer-set3.jpg", "/gods/mens-thermal-base-layer-set4.jpg", "/gods/mens-thermal-base-layer-set5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Warm base layer for cold weather activities.",
    features: ["Fleece-lined", "Moisture-wicking", "Top and bottom set", "Stretchy fabric"],
    specifications: { Material: "92% Polyester, 8% Spandex", Weight: "Heavyweight", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Dark Gray", "Light Gray"]
  },
  {
    id: "mf-014",
    name: "Casual Henley Shirt",
    category: "mens-fashion",
    price: 21.99,
    image: "/gods/mens-casual-henley-long-sleeve-shirt.jpg",
    images: ["/gods/mens-casual-henley-long-sleeve-shirt.jpg", "/gods/mens-casual-henley-long-sleeve-shirt1.jpg", "/gods/mens-casual-henley-long-sleeve-shirt2.jpg", "/gods/mens-casual-henley-long-sleeve-shirt3.jpg", "/gods/mens-casual-henley-long-sleeve-shirt4.jpg", "/gods/mens-casual-henley-long-sleeve-shirt5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Comfortable henley for casual everyday wear.",
    features: ["Soft cotton blend", "Button placket", "Long sleeves", "Multiple colors"],
    specifications: { Material: "60% Cotton, 40% Polyester", Fit: "Regular", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Dark Gray", "Light Gray", "Brown", "Green", "Purple", "Pink"]
  },
  {
    id: "mf-015",
    name: "Swim Trunks Quick-Dry",
    category: "mens-fashion",
    price: 24.99,
    image: "/gods/mens-swim-trunks-quick-dry.jpg",
    images: ["/gods/mens-swim-trunks-quick-dry.jpg", "/gods/mens-swim-trunks-quick-dry1.jpg", "/gods/mens-swim-trunks-quick-dry2.jpg", "/gods/mens-swim-trunks-quick-dry3.jpg", "/gods/mens-swim-trunks-quick-dry4.jpg", "/gods/mens-swim-trunks-quick-dry5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Quick-drying swim trunks for beach and pool.",
    features: ["Quick-dry fabric", "Mesh lining", "Elastic waistband", "Side pockets"],
    specifications: { Material: "100% Polyester", Inseam: "7 inches", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Orange", "Red", "Black", "Blue"]
  },
  {
    id: "mf-016",
    name: "Flannel Plaid Shirt",
    category: "mens-fashion",
    price: 28.99,
    image: "/gods/mens-flannel-plaid-button-up-shirt.jpg",
    images: ["/gods/mens-flannel-plaid-button-up-shirt.jpg", "/gods/mens-flannel-plaid-button-up-shirt1.jpg", "/gods/mens-flannel-plaid-button-up-shirt2.jpg", "/gods/mens-flannel-plaid-button-up-shirt3.jpg", "/gods/mens-flannel-plaid-button-up-shirt4.jpg", "/gods/mens-flannel-plaid-button-up-shirt5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Warm flannel shirt with classic plaid pattern.",
    features: ["100% cotton flannel", "Button-down collar", "Chest pockets", "Soft brushed finish"],
    specifications: { Material: "100% Cotton", Weight: "Midweight", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Red", "Brown", "Pink", "White"]
  },
  {
    id: "mf-017",
    name: "Compression Athletic Shirt",
    category: "mens-fashion",
    price: 26.99,
    image: "/gods/mens-compression-athletic-shirt.jpg",
    images: ["/gods/mens-compression-athletic-shirt.jpg", "/gods/mens-compression-athletic-shirt1.jpg", "/gods/mens-compression-athletic-shirt2.jpg", "/gods/mens-compression-athletic-shirt3.jpg", "/gods/mens-compression-athletic-shirt4.jpg", "/gods/mens-compression-athletic-shirt5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Compression shirt for enhanced athletic performance.",
    features: ["Compression fit", "Moisture-wicking", "Flatlock seams", "UV protection"],
    specifications: { Material: "87% Polyester, 13% Spandex", Fit: "Compression", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Dark Gray", "Light Gray"]
  },
  {
    id: "mf-018",
    name: "Chino Shorts Classic Fit",
    category: "mens-fashion",
    price: 29.99,
    image: "/gods/mens-chino-shorts-classic-fit.jpg",
    images: ["/gods/mens-chino-shorts-classic-fit.jpg", "/gods/mens-chino-shorts-classic-fit1.jpg", "/gods/mens-chino-shorts-classic-fit2.jpg", "/gods/mens-chino-shorts-classic-fit3.jpg", "/gods/mens-chino-shorts-classic-fit4.jpg", "/gods/mens-chino-shorts-classic-fit5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Versatile chino shorts for casual summer wear.",
    features: ["Cotton twill", "Classic fit", "Multiple pockets", "Belt loops"],
    specifications: { Material: "100% Cotton", Inseam: "9 inches", Sizes: "30-42" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "White"]
  },
  {
    id: "mf-019",
    name: "Hooded Sweatshirt",
    category: "mens-fashion",
    price: 36.99,
    image: "/gods/mens-hooded-sweatshirt-pullover.jpg",
    images: ["/gods/mens-hooded-sweatshirt-pullover.jpg", "/gods/mens-hooded-sweatshirt-pullover1.jpg", "/gods/mens-hooded-sweatshirt-pullover2.jpg", "/gods/mens-hooded-sweatshirt-pullover3.jpg", "/gods/mens-hooded-sweatshirt-pullover4.jpg", "/gods/mens-hooded-sweatshirt-pullover5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Comfortable hoodie for casual wear and layering.",
    features: ["Fleece-lined", "Kangaroo pocket", "Adjustable hood", "Ribbed cuffs"],
    specifications: { Material: "80% Cotton, 20% Polyester", Weight: "Heavyweight", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Fluorescent Green", "Red", "White", "Blue Red", "Gray", "Number White"]
  },
  {
    id: "mf-020",
    name: "Performance Track Pants",
    category: "mens-fashion",
    price: 31.99,
    image: "/gods/mens-performance-track-pants.jpg",
    images: ["/gods/mens-performance-track-pants.jpg", "/gods/mens-performance-track-pants1.jpg", "/gods/mens-performance-track-pants2.jpg", "/gods/mens-performance-track-pants3.jpg", "/gods/mens-performance-track-pants4.jpg", "/gods/mens-performance-track-pants5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Athletic pants for training and casual wear.",
    features: ["Moisture-wicking", "Zippered pockets", "Elastic waistband", "Tapered fit"],
    specifications: { Material: "100% Polyester", Fit: "Tapered", Sizes: "S-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Dark Gray", "Light Gray"]
  },
  // Women's Fashion (20 products)
  {
    id: "wf-001",
    name: "Flowy Chiffon Maxi Dress",
    category: "womens-fashion",
    price: 39.99,
    originalPrice: 59.99,
    image: "/gods/womens-flowy-chiffon-maxi-dress.jpg",
    images: ["/gods/womens-flowy-chiffon-maxi-dress.jpg", "/gods/womens-flowy-chiffon-maxi-dress1.jpg", "/gods/womens-flowy-chiffon-maxi-dress2.jpg", "/gods/womens-flowy-chiffon-maxi-dress3.jpg", "/gods/womens-flowy-chiffon-maxi-dress4.jpg", "/gods/womens-flowy-chiffon-maxi-dress5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Elegant maxi dress perfect for special occasions.",
    features: ["Lightweight chiffon", "Flowy silhouette", "Adjustable straps", "Lined"],
    specifications: { Material: "100% Polyester Chiffon", Length: "Maxi", Sizes: "XS-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "wf-002",
    name: "High-Waist Skinny Jeans",
    category: "womens-fashion",
    price: 42.99,
    originalPrice: 64.99,
    image: "/gods/womens-high-waist-skinny-jeans.jpg",
    images: ["/gods/womens-high-waist-skinny-jeans.jpg", "/gods/womens-high-waist-skinny-jeans1.jpg", "/gods/womens-high-waist-skinny-jeans2.jpg", "/gods/womens-high-waist-skinny-jeans3.jpg", "/gods/womens-high-waist-skinny-jeans4.jpg", "/gods/womens-high-waist-skinny-jeans5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Flattering high-waist jeans with stretch comfort.",
    features: ["High-rise waist", "4-way stretch", "Slimming fit", "Multiple washes"],
    specifications: { Material: "76% Cotton, 22% Polyester, 2% Spandex", Rise: "High", Sizes: "24-34" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Dark Blue", "Light Blue"]
  },
  {
    id: "wf-003",
    name: "UV Protection Cardigan",
    category: "womens-fashion",
    price: 27.99,
    image: "/gods/womens-uv-protection-cardigan.jpg",
    images: ["/gods/womens-uv-protection-cardigan.jpg", "/gods/womens-uv-protection-cardigan1.jpg", "/gods/womens-uv-protection-cardigan2.jpg", "/gods/womens-uv-protection-cardigan3.jpg", "/gods/womens-uv-protection-cardigan4.jpg", "/gods/womens-uv-protection-cardigan5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Lightweight cardigan with sun protection.",
    features: ["UPF 50+ protection", "Breathable fabric", "Long sleeves", "Multiple colors"],
    specifications: { Material: "95% Polyester, 5% Spandex", Protection: "UPF 50+", Sizes: "S-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Pink", "Green", "Black", "White", "Purple", "Yellow"],
  },
  {
    id: "wf-004",
    name: "Seamless Sports Bra",
    category: "womens-fashion",
    price: 19.99,
    image: "/gods/womens-seamless-sports-bra.jpg",
    images: ["/gods/womens-seamless-sports-bra.jpg", "/gods/womens-seamless-sports-bra1.jpg", "/gods/womens-seamless-sports-bra2.jpg", "/gods/womens-seamless-sports-bra3.jpg", "/gods/womens-seamless-sports-bra4.jpg", "/gods/womens-seamless-sports-bra5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Comfortable sports bra for medium-impact activities.",
    features: ["Seamless design", "Removable pads", "Moisture-wicking", "Medium support"],
    specifications: { Material: "92% Nylon, 8% Spandex", Support: "Medium", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "wf-005",
    name: "Pleated Midi Skirt",
    category: "womens-fashion",
    price: 32.99,
    originalPrice: 49.99,
    image: "/gods/womens-pleated-midi-skirt.jpg",
    images: ["/gods/womens-pleated-midi-skirt.jpg", "/gods/womens-pleated-midi-skirt1.jpg", "/gods/womens-pleated-midi-skirt2.jpg", "/gods/womens-pleated-midi-skirt3.jpg", "/gods/womens-pleated-midi-skirt4.jpg", "/gods/womens-pleated-midi-skirt5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Elegant pleated skirt for office and casual wear.",
    features: ["Accordion pleats", "Elastic waistband", "Midi length", "Flowy fabric"],
    specifications: { Material: "100% Polyester", Length: "Midi (knee-length)", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "wf-006",
    name: "Casual T-Shirt 3-Pack",
    category: "womens-fashion",
    price: 24.99,
    originalPrice: 49.99,
    image: "/gods/womens-casual-t-shirt-3-pack.jpg",
    images: ["/gods/womens-casual-t-shirt-3-pack.jpg", "/gods/womens-casual-t-shirt-3-pack1.jpg", "/gods/womens-casual-t-shirt-3-pack2.jpg", "/gods/womens-casual-t-shirt-3-pack3.jpg", "/gods/womens-casual-t-shirt-3-pack4.jpg", "/gods/womens-casual-t-shirt-3-pack5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Essential basic tees for everyday wear.",
    features: ["Soft cotton blend", "Crew neck", "Pack of 3", "Multiple colors"],
    specifications: { Material: "95% Cotton, 5% Spandex", Fit: "Regular", Sizes: "XS-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Brown"]
  },
  {
    id: "wf-007",
    name: "Yoga Leggings High-Waist",
    category: "womens-fashion",
    price: 29.99,
    originalPrice: 44.99,
    image: "/gods/womens-yoga-leggings-high-waist.jpg",
    images: ["/gods/womens-yoga-leggings-high-waist.jpg", "/gods/womens-yoga-leggings-high-waist1.jpg", "/gods/womens-yoga-leggings-high-waist2.jpg", "/gods/womens-yoga-leggings-high-waist3.jpg", "/gods/womens-yoga-leggings-high-waist4.jpg", "/gods/womens-yoga-leggings-high-waist5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Premium leggings for yoga and fitness.",
    features: ["High-waist design", "Squat-proof", "Hidden pocket", "4-way stretch"],
    specifications: { Material: "87% Nylon, 13% Spandex", Compression: "Medium", Sizes: "XS-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Brown", "Black", "Gray", "Navy", "Pink", "Green"]
  },
  {
    id: "wf-008",
    name: "Knit Sweater Pullover",
    category: "womens-fashion",
    price: 36.99,
    originalPrice: 49.99,
    image: "/gods/womens-knit-sweater-pullover.jpg",
    images: ["/gods/womens-knit-sweater-pullover.jpg", "/gods/womens-knit-sweater-pullover1.jpg", "/gods/womens-knit-sweater-pullover2.jpg", "/gods/womens-knit-sweater-pullover3.jpg", "/gods/womens-knit-sweater-pullover4.jpg", "/gods/womens-knit-sweater-pullover5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Cozy knit sweater for cool weather.",
    features: ["Soft knit fabric", "Crew neck", "Ribbed cuffs", "Relaxed fit"],
    specifications: { Material: "60% Cotton, 40% Acrylic", Weight: "Midweight", Sizes: "S-XL", Note: "Please note the pattern when making the purchase" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "wf-009",
    name: "Wide-Leg Palazzo Pants",
    category: "womens-fashion",
    price: 34.99,
    originalPrice: 49.99,
    image: "/gods/womens-wide-leg-palazzo-pants.jpg",
    images: ["/gods/womens-wide-leg-palazzo-pants.jpg", "/gods/womens-wide-leg-palazzo-pants1.jpg", "/gods/womens-wide-leg-palazzo-pants2.jpg", "/gods/womens-wide-leg-palazzo-pants3.jpg", "/gods/womens-wide-leg-palazzo-pants4.jpg", "/gods/womens-wide-leg-palazzo-pants5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Comfortable wide-leg pants with elegant drape.",
    features: ["Flowy fabric", "Elastic waistband", "Wide leg", "Wrinkle-resistant"],
    specifications: { Material: "95% Polyester, 5% Spandex", Fit: "Wide leg", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Green", "Brown" ]
  },
  {
    id: "wf-010",
    name: "Denim Jacket Classic",
    category: "womens-fashion",
    price: 44.99,
    originalPrice: 69.99,
    image: "/gods/womens-denim-jacket-classic.jpg",
    images: ["/gods/womens-denim-jacket-classic.jpg", "/gods/womens-denim-jacket-classic1.jpg", "/gods/womens-denim-jacket-classic2.jpg", "/gods/womens-denim-jacket-classic3.jpg", "/gods/womens-denim-jacket-classic4.jpg", "/gods/womens-denim-jacket-classic5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Timeless denim jacket for layering.",
    features: ["100% cotton denim", "Button closure", "Chest pockets", "Classic fit"],
    specifications: { Material: "100% Cotton", Weight: "12oz denim", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "wf-011",
    name: "Silk Blend Camisole",
    category: "womens-fashion",
    price: 22.99,
    image: "/gods/womens-silk-blend-camisole.jpg",
    images: ["/gods/womens-silk-blend-camisole.jpg", "/gods/womens-silk-blend-camisole1.jpg", "/gods/womens-silk-blend-camisole2.jpg", "/gods/womens-silk-blend-camisole3.jpg", "/gods/womens-silk-blend-camisole4.jpg", "/gods/womens-silk-blend-camisole5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Luxurious camisole for layering or standalone wear.",
    features: ["Silk blend fabric", "Adjustable straps", "V-neck", "Multiple colors"],
    specifications: { Material: "95% Polyester, 5% Silk", Fit: "Regular", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Pink", "Green", "Brown", "Red"]
  },
  {
    id: "wf-012",
    name: "Athletic Shorts with Liner",
    category: "womens-fashion",
    price: 21.99,
    image: "/gods/womens-athletic-shorts-with-liner.jpg",
    images: ["/gods/womens-athletic-shorts-with-liner.jpg", "/gods/womens-athletic-shorts-with-liner1.jpg", "/gods/womens-athletic-shorts-with-liner2.jpg", "/gods/womens-athletic-shorts-with-liner3.jpg", "/gods/womens-athletic-shorts-with-liner4.jpg", "/gods/womens-athletic-shorts-with-liner5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Comfortable shorts for running and workouts.",
    features: ["Built-in liner", "Moisture-wicking", "Side pockets", "Reflective details"],
    specifications: { Material: "100% Polyester", Inseam: "3 inches", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Pink", "Green", "Purple"]
  },
  {
    id: "wf-013",
    name: "Wrap Blouse Elegant",
    category: "womens-fashion",
    price: 31.99,
    image: "/gods/womens-wrap-blouse-elegant.jpg",
    images: ["/gods/womens-wrap-blouse-elegant.jpg", "/gods/womens-wrap-blouse-elegant1.jpg", "/gods/womens-wrap-blouse-elegant2.jpg", "/gods/womens-wrap-blouse-elegant3.jpg", "/gods/womens-wrap-blouse-elegant4.jpg", "/gods/womens-wrap-blouse-elegant5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Flattering wrap blouse for office and events.",
    features: ["Wrap design", "V-neckline", "Tie waist", "Flowy sleeves"],
    specifications: { Material: "100% Polyester", Fit: "Wrap style", Sizes: "XS-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Pink", "Blue"]
  },
  {
    id: "wf-014",
    name: "Linen Blend Shorts",
    category: "womens-fashion",
    price: 26.99,
    image: "/gods/womens-linen-blend-shorts.jpg",
    images: ["/gods/womens-linen-blend-shorts.jpg", "/gods/womens-linen-blend-shorts1.jpg", "/gods/womens-linen-blend-shorts2.jpg", "/gods/womens-linen-blend-shorts3.jpg", "/gods/womens-linen-blend-shorts4.jpg", "/gods/womens-linen-blend-shorts5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Breathable linen shorts for summer comfort.",
    features: ["Linen blend", "Elastic waistband", "Side pockets", "Relaxed fit"],
    specifications: { Material: "55% Linen, 45% Cotton", Inseam: "5 inches", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Blue"]
  },
  {
    id: "wf-015",
    name: "Turtleneck Sweater",
    category: "womens-fashion",
    price: 33.99,
    image: "/gods/womens-turtleneck-sweater.jpg",
    images: ["/gods/womens-turtleneck-sweater.jpg", "/gods/womens-turtleneck-sweater1.jpg", "/gods/womens-turtleneck-sweater2.jpg", "/gods/womens-turtleneck-sweater3.jpg", "/gods/womens-turtleneck-sweater4.jpg", "/gods/womens-turtleneck-sweater5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Classic turtleneck for layering and warmth.",
    features: ["Ribbed knit", "Turtleneck", "Slim fit", "Soft fabric"],
    specifications: { Material: "70% Viscose, 30% Nylon", Fit: "Slim", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Skin Color", "Gray"]
  },
  {
    id: "wf-016",
    name: "Printed Maxi Skirt",
    category: "womens-fashion",
    price: 37.99,
    image: "/gods/womens-printed-maxi-skirt.jpg",
    images: ["/gods/womens-printed-maxi-skirt.jpg", "/gods/womens-printed-maxi-skirt1.jpg", "/gods/womens-printed-maxi-skirt2.jpg", "/gods/womens-printed-maxi-skirt3.jpg", "/gods/womens-printed-maxi-skirt4.jpg", "/gods/womens-printed-maxi-skirt5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Vibrant printed skirt for summer style.",
    features: ["Floral print", "Elastic waistband", "Maxi length", "Flowy fabric"],
    specifications: { Material: "100% Rayon", Length: "Maxi", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Green", "Pink"]
  },
  {
    id: "wf-017",
    name: "Cropped Hoodie",
    category: "womens-fashion",
    price: 28.99,
    image: "/gods/womens-cropped-hoodie.jpg",
    images: ["/gods/womens-cropped-hoodie.jpg", "/gods/womens-cropped-hoodie1.jpg", "/gods/womens-cropped-hoodie2.jpg", "/gods/womens-cropped-hoodie3.jpg", "/gods/womens-cropped-hoodie4.jpg", "/gods/womens-cropped-hoodie5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Trendy cropped hoodie for casual wear.",
    features: ["Cropped length", "Drawstring hood", "Kangaroo pocket", "Soft fleece"],
    specifications: { Material: "80% Cotton, 20% Polyester", Fit: "Cropped", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Skin Color", "Pink", "Brown", "Purple", "Yellow"]
  },
  {
    id: "wf-018",
    name: "Pencil Skirt Office",
    category: "womens-fashion",
    price: 29.99,
    image: "/gods/womens-pencil-skirt-office.jpg",
    images: ["/gods/womens-pencil-skirt-office.jpg", "/gods/womens-pencil-skirt-office1.jpg", "/gods/womens-pencil-skirt-office2.jpg", "/gods/womens-pencil-skirt-office3.jpg", "/gods/womens-pencil-skirt-office4.jpg", "/gods/womens-pencil-skirt-office5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Professional pencil skirt for office wear.",
    features: ["Stretch fabric", "Back slit", "Knee length", "Wrinkle-resistant"],
    specifications: { Material: "68% Polyester, 29% Rayon, 3% Spandex", Length: "Knee", Sizes: "XS-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Brown", "Silver"]
  },
  {
    id: "wf-019",
    name: "Lace Trim Camisole",
    category: "womens-fashion",
    price: 18.99,
    image: "/gods/womens-lace-trim-camisole.jpg",
    images: ["/gods/womens-lace-trim-camisole.jpg", "/gods/womens-lace-trim-camisole1.jpg", "/gods/womens-lace-trim-camisole2.jpg", "/gods/womens-lace-trim-camisole3.jpg", "/gods/womens-lace-trim-camisole4.jpg", "/gods/womens-lace-trim-camisole5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Delicate camisole with lace detailing.",
    features: ["Lace trim", "Adjustable straps", "Soft fabric", "Multiple colors"],
    specifications: { Material: "95% Rayon, 5% Spandex", Fit: "Regular", Sizes: "XS-XL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "wf-020",
    name: "Jogger Pants Casual",
    category: "womens-fashion",
    price: 32.99,
    image: "/gods/womens-jogger-pants-casual.jpg",
    images: ["/gods/womens-jogger-pants-casual.jpg", "/gods/womens-jogger-pants-casual1.jpg", "/gods/womens-jogger-pants-casual2.jpg", "/gods/womens-jogger-pants-casual3.jpg", "/gods/womens-jogger-pants-casual4.jpg", "/gods/womens-jogger-pants-casual5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Comfortable joggers for lounging and casual wear.",
    features: ["Soft fleece", "Elastic waistband", "Tapered leg", "Side pockets"],
    specifications: { Material: "80% Cotton, 20% Polyester", Fit: "Tapered", Sizes: "XS-XXL" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Skin Color", "Blue"]
  },

  // Outdoor & Camping (20 products)
  {
    id: "oc-001",
    name: "Instant Pop-Up Tent 4-Person",
    category: "outdoor-camping",
    price: 89.99,
    originalPrice: 129.99,
    image: "/gods/instant-pop-up-tent-4-person.jpg",
    images: ["/gods/instant-pop-up-tent-4-person.jpg", "/gods/instant-pop-up-tent-4-person1.jpg", "/gods/instant-pop-up-tent-4-person2.jpg", "/gods/instant-pop-up-tent-4-person3.jpg", "/gods/instant-pop-up-tent-4-person4.jpg", "/gods/instant-pop-up-tent-4-person5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Quick-setup tent perfect for camping trips.",
    features: ["Sets up in 60 seconds", "Waterproof coating", "Ventilation windows", "Carry bag included"],
    specifications: { Capacity: "4 persons", Dimensions: "240cm x 210cm x 130cm", Weight: "4.5kg" },
    colors: ["Blue", "Green", "Red"]
  },
  {
    id: "oc-002",
    name: "Mummy Sleeping Bag -10°C",
    category: "outdoor-camping",
    price: 54.99,
    originalPrice: 79.99,
    image: "/gods/mummy-sleeping-bag-cold-weather.jpg",
    images: ["/gods/mummy-sleeping-bag-cold-weather.jpg", "/gods/mummy-sleeping-bag-cold-weather1.jpg", "/gods/mummy-sleeping-bag-cold-weather2.jpg", "/gods/mummy-sleeping-bag-cold-weather3.jpg", "/gods/mummy-sleeping-bag-cold-weather4.jpg", "/gods/mummy-sleeping-bag-cold-weather5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Warm sleeping bag for cold weather camping.",
    features: ["Temperature rated -10°C", "Mummy shape", "Compression sack", "Water-resistant"],
    specifications: { "Temperature Rating": "-10°C", Fill: "Synthetic", Weight: "1.8kg" },
    colors: ["Blue", "Green", "Dark Blue"]
  },
  {
    id: "oc-003",
    name: "Waterproof Picnic Blanket",
    category: "outdoor-camping",
    price: 24.99,
    image: "/gods/waterproof-picnic-blanket-outdoor.jpg",
    images: ["/gods/waterproof-picnic-blanket-outdoor.jpg", "/gods/waterproof-picnic-blanket-outdoor1.jpg", "/gods/waterproof-picnic-blanket-outdoor2.jpg", "/gods/waterproof-picnic-blanket-outdoor3.jpg", "/gods/waterproof-picnic-blanket-outdoor4.jpg", "/gods/waterproof-picnic-blanket-outdoor5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Large waterproof blanket for picnics and beach.",
    features: ["Waterproof backing", "Folds compactly", "Carrying handle", "Machine washable"],
    specifications: { Size: "200cm x 200cm", Material: "Polyester with waterproof backing", Weight: "800g" },
    colors: ["Blue", "Green", "Pink"]
  },
  {
    id: "oc-004",
    name: "Portable Folding Chair",
    category: "outdoor-camping",
    price: 32.99,
    image: "/gods/portable-folding-camping-chair.jpg",
    images: ["/gods/portable-folding-camping-chair.jpg", "/gods/portable-folding-camping-chair1.jpg", "/gods/portable-folding-camping-chair2.jpg", "/gods/portable-folding-camping-chair3.jpg", "/gods/portable-folding-camping-chair4.jpg", "/gods/portable-folding-camping-chair5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Lightweight chair for camping and outdoor events.",
    features: ["Aluminum frame", "Cup holder", "Carry bag", "Supports 150kg"],
    specifications: { Material: "Aluminum + Oxford fabric", Weight: "2.2kg", "Load Capacity": "150kg" },
    colors: ["Black", "White"]
  },
  {
    id: "oc-005",
    name: "LED Camping Lantern Rechargeable",
    category: "outdoor-camping",
    price: 27.99,
    image: "/gods/led-camping-lantern-rechargeable.jpg",
    images: ["/gods/led-camping-lantern-rechargeable.jpg", "/gods/led-camping-lantern-rechargeable1.jpg", "/gods/led-camping-lantern-rechargeable2.jpg", "/gods/led-camping-lantern-rechargeable3.jpg", "/gods/led-camping-lantern-rechargeable4.jpg", "/gods/led-camping-lantern-rechargeable5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Bright LED lantern with multiple lighting modes.",
    features: ["1000 lumens", "USB rechargeable", "3 light modes", "Power bank function"],
    specifications: { Brightness: "1000 lumens", "Battery Life": "12-48 hours", "Charging Time": "4 hours" },

  },
  {
    id: "oc-006",
    name: "Portable Charcoal Grill",
    category: "outdoor-camping",
    price: 44.99,
    image: "/gods/portable-charcoal-grill-camping.jpg",
    images: ["/gods/portable-charcoal-grill-camping.jpg", "/gods/portable-charcoal-grill-camping1.jpg", "/gods/portable-charcoal-grill-camping2.jpg", "/gods/portable-charcoal-grill-camping3.jpg", "/gods/portable-charcoal-grill-camping4.jpg", "/gods/portable-charcoal-grill-camping5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Compact grill for outdoor cooking.",
    features: ["Foldable design", "Stainless steel", "Adjustable height", "Carry case included"],
    specifications: { Material: "Stainless Steel", "Cooking Area": "35cm x 27cm", Weight: "3.5kg" },
  },
  {
    id: "oc-007",
    name: "Trekking Poles Pair",
    category: "outdoor-camping",
    price: 29.99,
    originalPrice: 44.99,
    image: "/gods/trekking-poles-adjustable-pair.jpg",
    images: ["/gods/trekking-poles-adjustable-pair.jpg", "/gods/trekking-poles-adjustable-pair1.jpg", "/gods/trekking-poles-adjustable-pair2.jpg", "/gods/trekking-poles-adjustable-pair3.jpg", "/gods/trekking-poles-adjustable-pair4.jpg", "/gods/trekking-poles-adjustable-pair5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Adjustable poles for hiking and trekking.",
    features: ["Adjustable length", "Anti-shock system", "Cork grips", "Tungsten tips"],
    specifications: { Material: "Aluminum alloy", "Length Range": "65-135cm", Weight: "280g each" },
    colors: ["Blue", "Green", "Yellow"]
  },
  {
    id: "oc-008",
    name: "Camping Cookware Set",
    category: "outdoor-camping",
    price: 39.99,
    image: "/gods/camping-cookware-set-portable.jpg",
    images: ["/gods/camping-cookware-set-portable.jpg", "/gods/camping-cookware-set-portable1.jpg", "/gods/camping-cookware-set-portable2.jpg", "/gods/camping-cookware-set-portable3.jpg", "/gods/camping-cookware-set-portable4.jpg", "/gods/camping-cookware-set-portable5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Complete cookware set for outdoor cooking.",
    features: ["11-piece set", "Non-stick coating", "Nesting design", "Mesh carry bag"],
    specifications: { Pieces: "11", Material: "Aluminum with non-stick coating", Weight: "1.2kg" },
  },
  {
    id: "oc-009",
    name: "Inflatable Camping Pillow",
    category: "outdoor-camping",
    price: 14.99,
    image: "/gods/inflatable-camping-pillow-compact.jpg",
    images: ["/gods/inflatable-camping-pillow-compact.jpg", "/gods/inflatable-camping-pillow-compact1.jpg", "/gods/inflatable-camping-pillow-compact2.jpg", "/gods/inflatable-camping-pillow-compact3.jpg", "/gods/inflatable-camping-pillow-compact4.jpg", "/gods/inflatable-camping-pillow-compact5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Compact pillow for comfortable camping sleep.",
    features: ["Inflates in seconds", "Soft fabric cover", "Compact when deflated", "Adjustable firmness"],
    specifications: { Material: "TPU + Polyester", "Inflated Size": "40cm x 30cm x 12cm", Weight: "85g" },
    colors: ["Blue", "Green", "Blue", "Black", "Silver", "Red"]
  },
  {
    id: "oc-010",
    name: "Waterproof Dry Bag 20L",
    category: "outdoor-camping",
    price: 19.99,
    image: "/gods/waterproof-dry-bag-20l.jpg",
    images: ["/gods/waterproof-dry-bag-20l.jpg", "/gods/waterproof-dry-bag-20l1.jpg", "/gods/waterproof-dry-bag-20l2.jpg", "/gods/waterproof-dry-bag-20l3.jpg", "/gods/waterproof-dry-bag-20l4.jpg", "/gods/waterproof-dry-bag-20l5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Keep gear dry during water activities.",
    features: ["100% waterproof", "Roll-top closure", "Shoulder strap", "Durable PVC"],
    specifications: { Capacity: "20L", Material: "PVC tarpaulin", Waterproof: "IPX6" },
    colors: ["Blue", "Red", "Dark Green", "White"]
  },
  {
    id: "oc-011",
    name: "Camping Hammock with Mosquito Net",
    category: "outdoor-camping",
    price: 42.99,
    image: "/gods/camping-hammock-with-mosquito-net.jpg",
    images: ["/gods/camping-hammock-with-mosquito-net.jpg", "/gods/camping-hammock-with-mosquito-net1.jpg", "/gods/camping-hammock-with-mosquito-net2.jpg", "/gods/camping-hammock-with-mosquito-net3.jpg", "/gods/camping-hammock-with-mosquito-net4.jpg", "/gods/camping-hammock-with-mosquito-net5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Comfortable hammock with built-in bug protection.",
    features: ["Mosquito net included", "Supports 200kg", "Easy setup", "Carry bag"],
    specifications: { Material: "Parachute nylon", Dimensions: "290cm x 140cm", "Load Capacity": "200kg" },
  },
  {
    id: "oc-012",
    name: "Portable Water Filter",
    category: "outdoor-camping",
    price: 34.99,
    image: "/gods/portable-water-filter-camping.jpg",
    images: ["/gods/portable-water-filter-camping.jpg", "/gods/portable-water-filter-camping1.jpg", "/gods/portable-water-filter-camping2.jpg", "/gods/portable-water-filter-camping3.jpg", "/gods/portable-water-filter-camping4.jpg", "/gods/portable-water-filter-camping5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Purify water from natural sources safely.",
    features: ["Filters 99.99% bacteria", "1000L capacity", "Lightweight", "Fast flow rate"],
    specifications: { Capacity: "1000 liters", "Flow Rate": "1.7L/min", Weight: "56g" },
  },
  {
    id: "oc-013",
    name: "Camping Axe Multi-Tool",
    category: "outdoor-camping",
    price: 36.99,
    image: "/gods/camping-axe-multi-tool.jpg",
    images: ["/gods/camping-axe-multi-tool.jpg", "/gods/camping-axe-multi-tool1.jpg", "/gods/camping-axe-multi-tool2.jpg", "/gods/camping-axe-multi-tool3.jpg", "/gods/camping-axe-multi-tool4.jpg", "/gods/camping-axe-multi-tool5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Versatile axe for camping and survival.",
    features: ["Stainless steel blade", "Hammer head", "Nylon sheath", "Ergonomic handle"],
    specifications: { Material: "Stainless Steel + Fiberglass", Weight: "680g", Length: "38cm" },
  },
  {
    id: "oc-014",
    name: "Insulated Cooler Bag 30L",
    category: "outdoor-camping",
    price: 29.99,
    image: "/gods/insulated-cooler-bag-30l.jpg",
    images: ["/gods/insulated-cooler-bag-30l.jpg", "/gods/insulated-cooler-bag-30l1.jpg", "/gods/insulated-cooler-bag-30l2.jpg", "/gods/insulated-cooler-bag-30l4.jpg", "/gods/insulated-cooler-bag-30l5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Keep food and drinks cold for hours.",
    features: ["30L capacity", "Thick insulation", "Multiple pockets", "Shoulder strap"],
    specifications: { Capacity: "30L", Insulation: "PEVA lining", Dimensions: "40cm x 25cm x 30cm" },
  },
  {
    id: "oc-015",
    name: "Emergency Survival Kit",
    category: "outdoor-camping",
    price: 39.99,
    image: "/gods/emergency-survival-kit-camping.jpg",
    images: ["/gods/emergency-survival-kit-camping.jpg", "/gods/emergency-survival-kit-camping1.jpg", "/gods/emergency-survival-kit-camping2.jpg", "/gods/emergency-survival-kit-camping3.jpg", "/gods/emergency-survival-kit-camping4.jpg", "/gods/emergency-survival-kit-camping5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Comprehensive survival kit for emergencies.",
    features: ["40+ items", "First aid supplies", "Fire starter", "Compact case"],
    specifications: { Items: "40+", Weight: "1.1kg", Case: "Water-resistant" },
    colors: ["Red", "Blue"]
  },
  {
    id: "oc-016",
    name: "Solar Powered Charger",
    category: "outdoor-camping",
    price: 44.99,
    image: "/gods/solar-powered-charger-camping.jpg",
    images: ["/gods/solar-powered-charger-camping.jpg", "/gods/solar-powered-charger-camping1.jpg", "/gods/solar-powered-charger-camping2.jpg", "/gods/solar-powered-charger-camping3.jpg", "/gods/solar-powered-charger-camping4.jpg", "/gods/solar-powered-charger-camping5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Charge devices using solar power outdoors.",
    features: ["20W solar panel", "Dual USB ports", "Foldable design", "Weather-resistant"],
    specifications: { Power: "20W", Output: "5V/2.4A per port", Weight: "580g" },
  },
  {
    id: "oc-017",
    name: "Camping Cot Portable",
    category: "outdoor-camping",
    price: 64.99,
    originalPrice: 89.99,
    image: "/gods/camping-cot-portable-folding.jpg",
    images: ["/gods/camping-cot-portable-folding.jpg", "/gods/camping-cot-portable-folding1.jpg", "/gods/camping-cot-portable-folding2.jpg", "/gods/camping-cot-portable-folding3.jpg", "/gods/camping-cot-portable-folding4.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Elevated cot for comfortable camping sleep.",
    features: ["Aluminum frame", "Supports 150kg", "Folds flat", "Carry bag"],
    specifications: {
      Material: "Aluminum + Oxford fabric",
      Dimensions: "190cm x 65cm x 40cm",
      "Load Capacity": "150kg",
    },
  },
  {
    id: "oc-018",
    name: "Headlamp LED Rechargeable",
    category: "outdoor-camping",
    price: 22.99,
    image: "/gods/headlamp-led-rechargeable-camping.jpg",
    images: ["/gods/headlamp-led-rechargeable-camping.jpg", "/gods/headlamp-led-rechargeable-camping1.jpg", "/gods/headlamp-led-rechargeable-camping2.jpg", "/gods/headlamp-led-rechargeable-camping3.jpg", "/gods/headlamp-led-rechargeable-camping4.jpg", "/gods/headlamp-led-rechargeable-camping5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Hands-free lighting for night activities.",
    features: ["1200 lumens", "USB rechargeable", "5 light modes", "Waterproof IPX4"],
    specifications: { Brightness: "1200 lumens", "Battery Life": "4-30 hours", Weight: "95g" },
    colors: ["Orange", "Black"]
  },
  {
    id: "oc-019",
    name: "Camping Table Folding",
    category: "outdoor-camping",
    price: 37.99,
    image: "/gods/camping-table-folding-portable.jpg",
    images: ["/gods/camping-table-folding-portable.jpg", "/gods/camping-table-folding-portable1.jpg", "/gods/camping-table-folding-portable2.jpg", "/gods/camping-table-folding-portable3.jpg", "/gods/camping-table-folding-portable4.jpg", "/gods/camping-table-folding-portable5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Lightweight table for outdoor dining.",
    features: ["Aluminum construction", "Folds compactly", "Adjustable legs", "Carry handle"],
    specifications: { Material: "Aluminum", Dimensions: "70cm x 50cm x 60cm", Weight: "2.8kg" },
  },
  {
    id: "oc-020",
    name: "Camping Shower Bag",
    category: "outdoor-camping",
    price: 16.99,
    image: "/gods/camping-shower-bag-solar.jpg",
    images: ["/gods/camping-shower-bag-solar.jpg", "/gods/camping-shower-bag-solar1.jpg", "/gods/camping-shower-bag-solar2.jpg", "/gods/camping-shower-bag-solar3.jpg", "/gods/camping-shower-bag-solar4.jpg", "/gods/camping-shower-bag-solar5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Solar-heated shower for camping hygiene.",
    features: ["20L capacity", "Solar heating", "Temperature indicator", "Shower head included"],
    specifications: { Capacity: "20L", Material: "PVC", "Heating Time": "3 hours in sun" },
    colors: ["Black", "Brown", "White", "Skin Color"]
  },

  // Sports Equipment (20 products)
  {
    id: "se-001",
    name: "Premium Yoga Mat Non-Slip",
    category: "sports-equipment",
    price: 29.99,
    originalPrice: 44.99,
    image: "/gods/premium-yoga-mat-non-slip.jpg",
    images: ["/gods/premium-yoga-mat-non-slip.jpg", "/gods/premium-yoga-mat-non-slip1.jpg", "/gods/premium-yoga-mat-non-slip2.jpg", "/gods/premium-yoga-mat-non-slip3.jpg", "/gods/premium-yoga-mat-non-slip4.jpg", "/gods/premium-yoga-mat-non-slip5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "High-quality yoga mat with excellent grip and cushioning.",
    features: ["6mm thickness", "Non-slip surface", "Eco-friendly TPE", "Carrying strap included"],
    specifications: { Material: "TPE", Thickness: "6mm", Dimensions: "183cm x 61cm" },
    colors: ["Purple", "Pink", "Green", "Silver"]
  },
  {
    id: "se-002",
    name: "Speed Jump Rope with Counter",
    category: "sports-equipment",
    price: 12.99,
    image: "/gods/speed-jump-rope-with-counter.jpg",
    images: ["/gods/speed-jump-rope-with-counter.jpg", "/gods/speed-jump-rope-with-counter1.jpg", "/gods/speed-jump-rope-with-counter2.jpg", "/gods/speed-jump-rope-with-counter3.jpg", "/gods/speed-jump-rope-with-counter4.jpg", "/gods/speed-jump-rope-with-counter5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Professional jump rope with digital counter.",
    features: ["Digital counter", "Adjustable length", "Ball bearings", "Comfortable grips"],
    specifications: { Material: "Steel wire + PVC coating", Length: "Adjustable up to 3m", Weight: "180g" },
    colors: ["Pink", "Blue", "Brown"]
  },
  {
    id: "se-003",
    name: "Resistance Bands Set of 5",
    category: "sports-equipment",
    price: 19.99,
    image: "/gods/resistance-bands-set-of-5.jpg",
    images: ["/gods/resistance-bands-set-of-5.jpg", "/gods/resistance-bands-set-of-51.jpg", "/gods/resistance-bands-set-of-52.jpg", "/gods/resistance-bands-set-of-53.jpg", "/gods/resistance-bands-set-of-54.jpg", "/gods/resistance-bands-set-of-55.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Complete set of resistance bands for strength training.",
    features: ["5 resistance levels", "Natural latex", "Carry bag", "Exercise guide"],
    specifications: { Material: "Natural Latex", Resistance: "5-35 lbs", Dimensions: "30cm circumference" },
    colors: ["Black", "Blue", "Green", "Red", "Yellow"]
  },
  {
    id: "se-004",
    name: "Adjustable Dumbbells Pair",
    category: "sports-equipment",
    price: 89.99,
    originalPrice: 129.99,
    image: "/gods/adjustable-dumbbells-pair.jpg",
    images: ["/gods/adjustable-dumbbells-pair.jpg", "/gods/adjustable-dumbbells-pair1.jpg", "/gods/adjustable-dumbbells-pair2.jpg", "/gods/adjustable-dumbbells-pair3.jpg", "/gods/adjustable-dumbbells-pair4.jpg", "/gods/adjustable-dumbbells-pair5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Space-saving adjustable dumbbells for home workouts.",
    features: ["Adjustable 5-25 lbs", "Quick-change system", "Compact design", "Non-slip handles"],
    specifications: { "Weight Range": "5-25 lbs per dumbbell", Increments: "5 lbs", Material: "Steel + Rubber" },
  },
  {
    id: "se-005",
    name: "Folding Treadmill Electric",
    category: "sports-equipment",
    price: 399.99,
    originalPrice: 599.99,
    image: "/gods/folding-treadmill-electric.jpg",
    images: ["/gods/folding-treadmill-electric.jpg", "/gods/folding-treadmill-electric1.jpg", "/gods/folding-treadmill-electric2.jpg", "/gods/folding-treadmill-electric3.jpg", "/gods/folding-treadmill-electric4.jpg", "/gods/folding-treadmill-electric5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Compact treadmill perfect for home use.",
    features: ["Foldable design", "LCD display", "12 programs", "Max speed 12 km/h"],
    specifications: { "Motor Power": "2.5 HP", "Running Surface": "120cm x 40cm", "Max Weight": "120kg" },
    colors: ["Black", "Silver", "Pink"]
  },
  {
    id: "se-006",
    name: "Wrist Support Wraps Pair",
    category: "sports-equipment",
    price: 14.99,
    image: "/gods/wrist-support-wraps-pair.jpg",
    images: ["/gods/wrist-support-wraps-pair.jpg", "/gods/wrist-support-wraps-pair1.jpg", "/gods/wrist-support-wraps-pair2.jpg", "/gods/wrist-support-wraps-pair3.jpg", "/gods/wrist-support-wraps-pair4.jpg", "/gods/wrist-support-wraps-pair5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Professional wrist wraps for weightlifting.",
    features: ["18-inch length", "Thumb loop", "Adjustable tightness", "Breathable fabric"],
    specifications: { Length: "18 inches", Material: "Cotton + Elastic", Closure: "Velcro" },
    colors: ["Black", "Yellow", "Red", "Silver"]
  },
  {
    id: "se-007",
    name: "Ab Roller Wheel",
    category: "sports-equipment",
    price: 16.99,
    image: "/gods/ab-roller-wheel-exercise.jpg",
    images: ["/gods/ab-roller-wheel-exercise.jpg", "/gods/ab-roller-wheel-exercise1.jpg", "/gods/ab-roller-wheel-exercise2.jpg", "/gods/ab-roller-wheel-exercise3.jpg", "/gods/ab-roller-wheel-exercise4.jpg", "/gods/ab-roller-wheel-exercise5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Effective ab roller for core strengthening.",
    features: ["Dual wheels", "Non-slip handles", "Knee pad included", "Stable design"],
    specifications: { Material: "ABS + TPR", "Wheel Diameter": "18cm", "Max Load": "150kg" },
    colors: ["Black", "White", "Blue", "Red"]
  },
  {
    id: "se-008",
    name: "Exercise Ball with Pump",
    category: "sports-equipment",
    price: 18.99,
    image: "/gods/exercise-ball-with-pump.jpg",
    images: ["/gods/exercise-ball-with-pump.jpg", "/gods/exercise-ball-with-pump1.jpg", "/gods/exercise-ball-with-pump2.jpg", "/gods/exercise-ball-with-pump3.jpg", "/gods/exercise-ball-with-pump4.jpg", "/gods/exercise-ball-with-pump5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Versatile exercise ball for fitness and yoga.",
    features: ["Anti-burst design", "Multiple sizes", "Pump included", "Textured surface"],
    specifications: { Material: "PVC", Sizes: "55cm, 65cm, 75cm", "Max Load": "300kg" },
    colors: ["Purple", "Pink", "Red", "Blue", "Silver"]
  },
  {
    id: "se-009",
    name: "Foam Roller for Muscle Recovery",
    category: "sports-equipment",
    price: 21.99,
    image: "/gods/foam-roller-muscle-recovery.jpg",
    images: ["/gods/foam-roller-muscle-recovery.jpg", "/gods/foam-roller-muscle-recovery1.jpg", "/gods/foam-roller-muscle-recovery2.jpg", "/gods/foam-roller-muscle-recovery3.jpg", "/gods/foam-roller-muscle-recovery4.jpg", "/gods/foam-roller-muscle-recovery5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "High-density foam roller for muscle recovery.",
    features: ["High-density foam", "Textured surface", "Multiple sizes", "Carry bag"],
    specifications: { Material: "EVA Foam", Dimensions: "33cm x 14cm", Density: "High" },
    colors: ["Pink", "Brown", "White"]
  },
  {
    id: "se-010",
    name: "Kettlebell Cast Iron",
    category: "sports-equipment",
    price: 34.99,
    image: "/gods/kettlebell-cast-iron.jpg",
    images: ["/gods/kettlebell-cast-iron.jpg", "/gods/kettlebell-cast-iron1.jpg", "/gods/kettlebell-cast-iron2.jpg", "/gods/kettlebell-cast-iron3.jpg", "/gods/kettlebell-cast-iron4.jpg", "/gods/kettlebell-cast-iron5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Durable cast iron kettlebell for strength training.",
    features: ["Cast iron construction", "Wide handle", "Flat base", "Multiple weights"],
    specifications: { Material: "Cast Iron", Weights: "8kg, 12kg, 16kg, 20kg", Finish: "Powder coated" },
    colors: ["Black", "Pink", "Green", "Purple", "Light Gray"]
  },
  {
    id: "se-011",
    name: "Pull-Up Bar Doorway",
    category: "sports-equipment",
    price: 27.99,
    image: "/gods/pull-up-bar-doorway.jpg",
    images: ["/gods/pull-up-bar-doorway.jpg", "/gods/pull-up-bar-doorway1.jpg", "/gods/pull-up-bar-doorway2.jpg", "/gods/pull-up-bar-doorway3.jpg", "/gods/pull-up-bar-doorway4.jpg", "/gods/pull-up-bar-doorway5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Easy-install pull-up bar for doorways.",
    features: ["No screws needed", "Multiple grip positions", "Supports 150kg", "Foam grips"],
    specifications: { Material: "Steel", "Adjustable Width": "62-100cm", "Max Load": "150kg" },
  },
  {
    id: "se-012",
    name: "Ankle Weights Pair",
    category: "sports-equipment",
    price: 22.99,
    image: "/gods/ankle-weights-pair.jpg",
    images: ["/gods/ankle-weights-pair.jpg", "/gods/ankle-weights-pair1.jpg", "/gods/ankle-weights-pair2.jpg", "/gods/ankle-weights-pair3.jpg", "/gods/ankle-weights-pair4.jpg", "/gods/ankle-weights-pair5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Adjustable ankle weights for resistance training.",
    features: ["Adjustable weight", "Comfortable padding", "Secure straps", "Pair included"],
    specifications: { "Weight Range": "1-5 lbs per ankle", Material: "Neoprene + Iron sand", Closure: "Velcro" },
    colors: ["Black", "Pink", "Green", "Purple", "Light Gray", "Red"]
  },
  {
    id: "se-013",
    name: "Yoga Block Set",
    category: "sports-equipment",
    price: 15.99,
    image: "/gods/yoga-block-set-of-2.jpg",
    images: ["/gods/yoga-block-set-of-2.jpg", "/gods/yoga-block-set-of-21.jpg", "/gods/yoga-block-set-of-22.jpg", "/gods/yoga-block-set-of-23.jpg", "/gods/yoga-block-set-of-24.jpg", "/gods/yoga-block-set-of-25.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Supportive yoga blocks for better alignment.",
    features: ["High-density foam", "Non-slip surface", "Multiple colors"],
    specifications: { Material: "EVA Foam", Dimensions: "23cm x 15cm x 10cm", Weight: "150g each" },
    colors: ["Pink", "Brown", "White", "Green", "Blue"]
  },
  {
    id: "se-014",
    name: "Suspension Training Straps",
    category: "sports-equipment",
    price: 39.99,
    image: "/gods/suspension-training-straps.jpg",
    images: ["/gods/suspension-training-straps.jpg", "/gods/suspension-training-straps1.jpg", "/gods/suspension-training-straps2.jpg", "/gods/suspension-training-straps3.jpg", "/gods/suspension-training-straps4.jpg", "/gods/suspension-training-straps5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Versatile suspension trainer for full-body workouts.",
    features: ["Adjustable length", "Door anchor included", "Handles and foot cradles", "Carry bag"],
    specifications: { Material: "Nylon webbing", "Max Load": "180kg", "Length Range": "Adjustable" },
  },
  {
    id: "se-015",
    name: "Medicine Ball",
    category: "sports-equipment",
    price: 28.99,
    image: "/gods/medicine-ball-weighted.jpg",
    images: ["/gods/medicine-ball-weighted.jpg", "/gods/medicine-ball-weighted1.jpg", "/gods/medicine-ball-weighted2.jpg", "/gods/medicine-ball-weighted3.jpg", "/gods/medicine-ball-weighted4.jpg", "/gods/medicine-ball-weighted5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Weighted medicine ball for strength and conditioning.",
    features: ["Textured surface", "Durable rubber", "Multiple weights", "Easy to grip"],
    specifications: { Material: "Rubber", Weights: "4kg, 6kg, 8kg, 10kg", Diameter: "22-28cm" },
    colors: ["Purple", "Blue", "Green", "Orange", "Pink"]
  },
  {
    id: "se-016",
    name: "Agility Ladder",
    category: "sports-equipment",
    price: 17.99,
    image: "/gods/agility-ladder-training.jpg",
    images: ["/gods/agility-ladder-training.jpg", "/gods/agility-ladder-training1.jpg", "/gods/agility-ladder-training2.jpg", "/gods/agility-ladder-training3.jpg", "/gods/agility-ladder-training4.jpg", "/gods/agility-ladder-training5.jpg"],
    rating: 4.5,
        inStock: true,
    description: "Improve speed and agility with this training ladder.",
    features: ["12 adjustable rungs", "Carry bag", "Ground stakes", "Durable nylon"],
    specifications: { Length: "6 meters", Rungs: "12", Material: "Nylon + Plastic" },
    colors: ["Blue", "Yellow"]
  },
  {
    id: "se-017",
    name: "Push-Up Bars",
    category: "sports-equipment",
    price: 19.99,
    image: "/gods/push-up-bars-exercise.jpg",
    images: ["/gods/push-up-bars-exercise.jpg", "/gods/push-up-bars-exercise1.jpg", "/gods/push-up-bars-exercise2.jpg", "/gods/push-up-bars-exercise3.jpg", "/gods/push-up-bars-exercise4.jpg", "/gods/push-up-bars-exercise5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Ergonomic push-up bars for better form.",
    features: ["Foam grips", "Non-slip base", "Supports 150kg", "Compact design"],
    specifications: { Material: "Steel + Foam", Dimensions: "23cm x 15cm", "Max Load": "150kg" },
  },
  {
    id: "se-018",
    name: "Weighted Jump Rope",
    category: "sports-equipment",
    price: 24.99,
    image: "/gods/weighted-jump-rope.jpg",
    images: ["/gods/weighted-jump-rope.jpg", "/gods/weighted-jump-rope1.jpg", "/gods/weighted-jump-rope2.jpg", "/gods/weighted-jump-rope3.jpg", "/gods/weighted-jump-rope4.jpg", "/gods/weighted-jump-rope5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Heavy jump rope for intense cardio workouts.",
    features: ["Weighted handles", "Adjustable length", "Ball bearings", "Durable cable"],
    specifications: { "Handle Weight": "0.5 lbs each", Material: "Steel cable + PVC", Length: "Adjustable" },
    colors: ["Black", "Green", "Blue", 'Brown', "Black Orange", "Pink"]
  },
  {
    id: "se-019",
    name: "Balance Board",
    category: "sports-equipment",
    price: 32.99,
    image: "/gods/balance-board-training.jpg",
    images: ["/gods/balance-board-training.jpg", "/gods/balance-board-training1.jpg", "/gods/balance-board-training2.jpg", "/gods/balance-board-training3.jpg", "/gods/balance-board-training4.jpg", "/gods/balance-board-training5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Improve balance and core strength.",
    features: ["Non-slip surface", "Wooden construction", "Multiple difficulty levels", "Supports 150kg"],
    specifications: { Material: "Wood + Cork", Diameter: "40cm", "Max Load": "150kg" },
  },
  {
    id: "se-020",
    name: "Resistance Tubes with Handles",
    category: "sports-equipment",
    price: 26.99,
    image: "/gods/resistance-tubes-with-handles.jpg",
    images: ["/gods/resistance-tubes-with-handles.jpg", "/gods/resistance-tubes-with-handles1.jpg", "/gods/resistance-tubes-with-handles2.jpg", "/gods/resistance-tubes-with-handles3.jpg", "/gods/resistance-tubes-with-handles4.jpg", "/gods/resistance-tubes-with-handles5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Versatile resistance tubes for full-body training.",
    features: ["5 tubes included", "Comfortable handles", "Door anchor", "Ankle straps"],
    specifications: {
      Material: "Latex tubes",
      Resistance: "Up to 150 lbs combined",
      Includes: "Handles, anchor, straps",
    },
    colors: ["Gold", "Silver"]
  },
  // Purple Clay Teapots (20 products)
  {
    id: "tp-001",
    name: "Yixing Zisha Teapot",
    category: "creative-decor",
    price: 129.99,
    originalPrice: 179.99,
    image: "/gods/yixing-zisha-teapot-traditional.jpg",
    images: ["/gods/yixing-zisha-teapot-traditional.jpg", "/gods/yixing-zisha-teapot-traditional1.jpg", "/gods/yixing-zisha-teapot-traditional2.jpg", "/gods/yixing-zisha-teapot-traditional3.jpg", "/gods/yixing-zisha-teapot-traditional4.jpg", "/gods/yixing-zisha-teapot-traditional5.jpg"],
    rating: 4.9,
        inStock: true,
    description: "Authentic Yixing Zisha clay teapot for tea connoisseurs.",
    features: ["Handmade Zisha clay", "Enhances tea flavor", "Traditional design", "Includes infuser"],
    specifications: { Material: "Zisha Clay", Capacity: "250ml", Style: "Teapot" },
  },
  {
    id: "tp-002",
    name: "Purple Clay Gong Dao Bei",
    category: "creative-decor",
    price: 49.99,
    image: "/gods/purple-clay-gong-dao-bei-fairness-cup.jpg",
    images: ["/gods/purple-clay-gong-dao-bei-fairness-cup.jpg", "/gods/purple-clay-gong-dao-bei-fairness-cup2.jpg", "/gods/purple-clay-gong-dao-bei-fairness-cup3.jpg", "/gods/purple-clay-gong-dao-bei-fairness-cup4.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Purple clay fairness cup for serving tea.",
    features: ["Zisha clay material", "Even tea distribution", "Elegant design", "Durable"],
    specifications: { Material: "Purple Clay", Capacity: "200ml", Style: "Fairness cup" },
  },
  {
    id: "tp-003",
    name: "Miniature Teapot Set",
    category: "creative-decor",
    price: 69.99,
    image: "/gods/miniature-teapot-set-purple-clay.jpg",
    images: ["/gods/miniature-teapot-set-purple-clay.jpg", "/gods/miniature-teapot-set-purple-clay1.jpg", "/gods/miniature-teapot-set-purple-clay2.jpg", "/gods/miniature-teapot-set-purple-clay3.jpg", "/gods/miniature-teapot-set-purple-clay4.jpg", "/gods/miniature-teapot-set-purple-clay5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Charming miniature teapot set for display or small servings.",
    features: ["Set includes teapot and cups", "Handcrafted purple clay", "Decorative piece", "Unique gift"],
    specifications: { Material: "Purple Clay", Style: "Miniature tea set" },
  },
  {
    id: "tp-004",
    name: "Vintage Zisha Tea Urn",
    category: "creative-decor",
    price: 189.99,
    originalPrice: 249.99,
    image: "/gods/vintage-zisha-tea-urn-storage.jpg",
    images: ["/gods/vintage-zisha-tea-urn-storage.jpg", "/gods/vintage-zisha-tea-urn-storage1.jpg", "/gods/vintage-zisha-tea-urn-storage2.jpg", "/gods/vintage-zisha-tea-urn-storage3.jpg", "/gods/vintage-zisha-tea-urn-storage4.jpg", "/gods/vintage-zisha-tea-urn-storage5.jpg"],
    rating: 4.9,
        inStock: true,
    description: "Aged Zisha clay tea urn for storing and aging tea.",
    features: ["Aged Zisha clay", "Airtight seal", "Preserves tea aroma", "Collector's item"],
    specifications: { Material: "Zisha Clay", Capacity: "1000ml", Style: "Tea urn" },
  },
  {
    id: "tp-005",
    name: "Purple Clay Tea Pet",
    category: "creative-decor",
    price: 24.99,
    image: "/gods/purple-clay-tea-pet-buddha.jpg",
    images: ["/gods/purple-clay-tea-pet-buddha.jpg", "/gods/purple-clay-tea-pet-buddha1.jpg", "/gods/purple-clay-tea-pet-buddha2.jpg", "/gods/purple-clay-tea-pet-buddha3.jpg", "/gods/purple-clay-tea-pet-buddha4.jpg", "/gods/purple-clay-tea-pet-buddha5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Decorative purple clay tea pet.",
    features: ["Handmade Zisha clay", "Various shapes (Buddha shown)", "Enhances tea ceremony"],
    specifications: { Material: "Purple Clay", Style: "Tea pet" },
  },
  {
    id: "tp-006",
    name: "Hand-Painted Purple Clay Teapot",
    category: "creative-decor",
    price: 159.99,
    image: "/gods/hand-painted-purple-clay-teapot-landscape.jpg",
    images: ["/gods/hand-painted-purple-clay-teapot-landscape.jpg", "/gods/hand-painted-purple-clay-teapot-landscape1.jpg", "/gods/hand-painted-purple-clay-teapot-landscape2.jpg", "/gods/hand-painted-purple-clay-teapot-landscape3.jpg", "/gods/hand-painted-purple-clay-teapot-landscape4.jpg", "/gods/hand-painted-purple-clay-teapot-landscape5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Exquisite teapot with hand-painted landscape scenes.",
    features: ["Painted Zisha clay", "Artistic design", "Smooth pouring spout", "Unique gift"],
    specifications: { Material: "Zisha Clay", Capacity: "300ml", Style: "Painted teapot" },
  },
  {
    id: "tp-007",
    name: "Zisha Tea Set (4-Piece)",
    category: "creative-decor",
    price: 229.99,
    image: "/gods/zisha-tea-set-4-piece.jpg",
    images: ["/gods/zisha-tea-set-4-piece.jpg", "/gods/zisha-tea-set-4-piece1.jpg", "/gods/zisha-tea-set-4-piece2.jpg", "/gods/zisha-tea-set-4-piece3.jpg", "/gods/zisha-tea-set-4-piece4.jpg", "/gods/zisha-tea-set-4-piece5.jpg"],
    rating: 4.9,
        inStock: true,
    description: "Complete Zisha clay tea set for an authentic tea experience.",
    features: ["Includes teapot, fairness cup, 2 cups", "High-quality Zisha clay", "Elegant presentation"],
    specifications: { Material: "Zisha Clay", Pieces: "4", Style: "Tea set" },
  },
  {
    id: "tp-008",
    name: "Purple Clay Gaiwan",
    category: "creative-decor",
    price: 59.99,
    image: "/gods/purple-clay-gaiwan-lid-cup.jpg",
    images: ["/gods/purple-clay-gaiwan-lid-cup.jpg", "/gods/purple-clay-gaiwan-lid-cup2.jpg", "/gods/purple-clay-gaiwan-lid-cup3.jpg", "/gods/purple-clay-gaiwan-lid-cup4.jpg", "/gods/purple-clay-gaiwan-lid-cup5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Versatile purple clay gaiwan for brewing tea.",
    features: ["Zisha clay construction", "Brew and drink from one vessel", "Easy to use", "Durable"],
    specifications: { Material: "Purple Clay", Capacity: "150ml", Style: "Gaiwan" },
  },
  {
    id: "tp-009",
    name: "Dragon-Shaped Zisha Teapot",
    category: "creative-decor",
    price: 199.99,
    image: "/gods/dragon-shaped-zisha-teapot.jpg",
    images: ["/gods/dragon-shaped-zisha-teapot.jpg", "/gods/dragon-shaped-zisha-teapot1.jpg", "/gods/dragon-shaped-zisha-teapot2.jpg", "/gods/dragon-shaped-zisha-teapot3.jpg", "/gods/dragon-shaped-zisha-teapot4.jpg", "/gods/dragon-shaped-zisha-teapot5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Impressive teapot shaped like a dragon.",
    features: ["Intricate dragon carving", "Zisha clay", "Symbol of power", "Unique collectible"],
    specifications: { Material: "Zisha Clay", Capacity: "350ml", Style: "Sculptural teapot" },
  },
  {
    id: "tp-010",
    name: "Purple Clay Tea Caddy",
    category: "creative-decor",
    price: 79.99,
    image: "/gods/purple-clay-tea-caddy-storage.jpg",
    images: ["/gods/purple-clay-tea-caddy-storage.jpg", "/gods/purple-clay-tea-caddy-storage1.jpg", "/gods/purple-clay-tea-caddy-storage2.jpg", "/gods/purple-clay-tea-caddy-storage3.jpg", "/gods/purple-clay-tea-caddy-storage4.jpg", "/gods/purple-clay-tea-caddy-storage5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Airtight purple clay container for storing tea leaves.",
    features: ["Zisha clay", "Airtight seal", "Preserves freshness", "Elegant storage"],
    specifications: { Material: "Purple Clay", Capacity: "150g tea", Style: "Tea caddy" },
  },
  {
    id: "tp-011",
    name: "Phoenix-Design Zisha Teapot",
    category: "creative-decor",
    price: 169.99,
    image: "/gods/phoenix-design-zisha-teapot.jpg",
    images: ["/gods/phoenix-design-zisha-teapot.jpg", "/gods/phoenix-design-zisha-teapot1.jpg", "/gods/phoenix-design-zisha-teapot2.jpg", "/gods/phoenix-design-zisha-teapot3.jpg", "/gods/phoenix-design-zisha-teapot4.jpg", "/gods/phoenix-design-zisha-teapot5.jpg"],
    rating: 4.9,
        inStock: true,
    description: "Elegant teapot featuring a phoenix motif.",
    features: ["Zisha clay with phoenix design", "Symbol of good fortune", "Beautiful craftsmanship", "Gift ready"],
    specifications: { Material: "Zisha Clay", Capacity: "280ml", Style: "Artistic teapot" },
  },
  {
    id: "tp-012",
    name: "Purple Clay Tea Tray",
    category: "creative-decor",
    price: 89.99,
    image: "/gods/purple-clay-tea-tray-drainage.jpg",
    images: ["/gods/purple-clay-tea-tray-drainage.jpg", "/gods/purple-clay-tea-tray-drainage1.jpg", "/gods/purple-clay-tea-tray-drainage2.jpg", "/gods/purple-clay-tea-tray-drainage3.jpg", "/gods/purple-clay-tea-tray-drainage4.jpg", "/gods/purple-clay-tea-tray-drainage5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Functional purple clay tea tray with drainage.",
    features: ["Zisha clay", "Water collection reservoir", "Durable and practical", "Enhances tea ceremony"],
    specifications: { Material: "Purple Clay", Dimensions: "30x20cm", Style: "Tea tray" },
    colors: ["Dark Color", "Light Color"]
  },
  {
    id: "tp-013",
    name: "Emperor-Style Zisha Teapot",
    category: "creative-decor",
    price: 249.99,
    originalPrice: 329.99,
    image: "/gods/emperor-style-zisha-teapot-ornate.jpg",
    images: ["/gods/emperor-style-zisha-teapot-ornate.jpg", "/gods/emperor-style-zisha-teapot-ornate1.jpg", "/gods/emperor-style-zisha-teapot-ornate2.jpg", "/gods/emperor-style-zisha-teapot-ornate3.jpg", "/gods/emperor-style-zisha-teapot-ornate4.jpg", "/gods/emperor-style-zisha-teapot-ornate5.jpg"],
    rating: 4.9,
        inStock: true,
    description: "Ornate Zisha teapot inspired by imperial designs.",
    features: ["Intricate details", "High-quality Zisha clay", "Luxurious feel", "Collector's piece"],
    specifications: { Material: "Zisha Clay", Capacity: "400ml", Style: "Imperial teapot" },
    colors: ["Dark Color", "Light Color"]
  },
  {
    id: "tp-014",
    name: "Purple Clay Tea Cup Set",
    category: "creative-decor",
    price: 79.99,
    image: "/gods/purple-clay-tea-cup-set-drinking.jpg",
    images: ["/gods/purple-clay-tea-cup-set-drinking.jpg", "/gods/purple-clay-tea-cup-set-drinking1.jpg", "/gods/purple-clay-tea-cup-set-drinking2.jpg", "/gods/purple-clay-tea-cup-set-drinking3.jpg", "/gods/purple-clay-tea-cup-set-drinking4.jpg", "/gods/purple-clay-tea-cup-set-drinking5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Set of four purple clay tea cups.",
    features: ["Handmade Zisha cups", "Comfortable to hold", "Set of 4", "Enhances tea aroma"],
    specifications: { Material: "Purple Clay", Quantity: "4 pieces", Style: "Tea cups" },
    colors: ["Dark Color", "Light Color"]
  },
  {
    id: "tp-015",
    name: "Zisha Infuser Tea Pot",
    category: "creative-decor",
    price: 99.99,
    image: "/gods/zisha-infuser-tea-pot-modern.jpg",
    images: ["/gods/zisha-infuser-tea-pot-modern.jpg", "/gods/zisha-infuser-tea-pot-modern1.jpg", "/gods/zisha-infuser-tea-pot-modern2.jpg", "/gods/zisha-infuser-tea-pot-modern3.jpg", "/gods/zisha-infuser-tea-pot-modern4.jpg", "/gods/zisha-infuser-tea-pot-modern5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Modern Zisha clay teapot with built-in infuser.",
    features: ["Integrated infuser basket", "Zisha clay", "Easy to brew loose leaf", "Sleek design"],
    specifications: { Material: "Zisha Clay", Capacity: "200ml", Style: "Infuser teapot" },
  },
  {
    id: "tp-016",
    name: "Purple Clay Tea Boat",
    category: "creative-decor",
    price: 64.99,
    image: "/gods/purple-clay-tea-boat-ceremony.jpg",
    images: ["/gods/purple-clay-tea-boat-ceremony.jpg", "/gods/purple-clay-tea-boat-ceremony1.jpg", "/gods/purple-clay-tea-boat-ceremony2.jpg", "/gods/purple-clay-tea-boat-ceremony3.jpg", "/gods/purple-clay-tea-boat-ceremony4.jpg", "/gods/purple-clay-tea-boat-ceremony5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Decorative purple clay 'tea boat' for tea ceremony.",
    features: ["Zisha clay crafting", "Symbolic piece", "Adds elegance", "For display"],
    specifications: { Material: "Purple Clay", Dimensions: "15x10cm", Style: "Tea ceremony accessory" },
  },
  {
    id: "tp-017",
    name: "Traditional Chinese Teapot Set",
    category: "creative-decor",
    price: 199.99,
    image: "/gods/traditional-chinese-teapot-set-porcelain.jpg",
    images: ["/gods/traditional-chinese-teapot-set-porcelain.jpg", "/gods/traditional-chinese-teapot-set-porcelain1.jpg", "/gods/traditional-chinese-teapot-set-porcelain2.jpg", "/gods/traditional-chinese-teapot-set-porcelain3.jpg", "/gods/traditional-chinese-teapot-set-porcelain4.jpg", "/gods/traditional-chinese-teapot-set-porcelain5.jpg"],
    rating: 4.8,
        inStock: true,
    description: "Classic porcelain teapot set with traditional motifs.",
    features: ["Fine porcelain", "Includes teapot, cups, tray", "Intricate painting", "Gift packaging"],
    specifications: { Material: "Porcelain", Style: "Chinese tea set" },
  },
  {
    id: "tp-018",
    name: "Purple Clay Animal Teapot",
    category: "creative-decor",
    price: 149.99,
    image: "/gods/purple-clay-animal-teapot-frog.jpg",
    images: ["/gods/purple-clay-animal-teapot-frog.jpg", "/gods/purple-clay-animal-teapot-frog1.jpg", "/gods/purple-clay-animal-teapot-frog2.jpg", "/gods/purple-clay-animal-teapot-frog3.jpg", "/gods/purple-clay-animal-teapot-frog4.jpg", "/gods/purple-clay-animal-teapot-frog5.jpg"],
    rating: 4.6,
        inStock: true,
    description: "Playful teapot shaped like an animal.",
    features: ["Zisha clay", "Animal design (frog shown)", "Whimsical and functional"],
    specifications: { Material: "Purple Clay", Capacity: "200ml", Style: "Animal teapot" },
  },
  {
    id: "tp-019",
    name: "Handmade Zisha Tea Ware Set",
    category: "creative-decor",
    price: 299.99,
    image: "/gods/handmade-zisha-tea-ware-set-luxury.jpg",
    images: ["/gods/handmade-zisha-tea-ware-set-luxury.jpg", "/gods/handmade-zisha-tea-ware-set-luxury1.jpg", "/gods/handmade-zisha-tea-ware-set-luxury2.jpg", "/gods/handmade-zisha-tea-ware-set-luxury3.jpg", "/gods/handmade-zisha-tea-ware-set-luxury4.jpg"],
    rating: 4.9,
        inStock: true,
    description: "Luxury handmade Zisha tea ware set.",
    features: ["Complete tea set", "Premium Zisha clay", "Master craftsmanship", "Unparalleled quality"],
    specifications: { Material: "Zisha Clay", Style: "Luxury tea set" },
  },
  {
    id: "tp-020",
    name: "Purple Clay Tea Warmer",
    category: "creative-decor",
    price: 54.99,
    image: "/gods/purple-clay-tea-warmer-candle.jpg",
    images: ["/gods/purple-clay-tea-warmer-candle.jpg", "/gods/purple-clay-tea-warmer-candle1.jpg", "/gods/purple-clay-tea-warmer-candle2.jpg", "/gods/purple-clay-tea-warmer-candle3.jpg", "/gods/purple-clay-tea-warmer-candle4.jpg", "/gods/purple-clay-tea-warmer-candle5.jpg"],
    rating: 4.7,
        inStock: true,
    description: "Purple clay tea warmer to keep tea hot.",
    features: ["Zisha clay construction", "Uses tea light candle", "Keeps pot warm", "Elegant design"],
    specifications: { Material: "Purple Clay", Style: "Tea warmer" },
  },
]

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId)
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.originalPrice).slice(0, 8)
}
