export interface Product {
  id: string
  name: string
  category: string
  price: number
  originalPrice?: number
  image: string
  rating: number
  reviews: number
  inStock: boolean
  description: string
  features: string[]
  specifications: Record<string, string>
}

export const categories = [
  { id: "daily-essentials", name: "Daily Essentials", icon: "🏠" },
  { id: "mens-fashion", name: "Men's Fashion", icon: "👔" },
  { id: "womens-fashion", name: "Women's Fashion", icon: "👗" },
  { id: "outdoor-camping", name: "Outdoor & Camping", icon: "⛺" },
  { id: "sports-equipment", name: "Sports Equipment", icon: "🏋️" },
  { id: "puer-tea", name: "Pu-er Tea", icon: "🍵" },
  { id: "jade-jewelry", name: "Jade & Jewelry", icon: "💎" },
  { id: "teapots", name: "Purple Clay Teapots", icon: "🫖" },
]

export const products: Product[] = [
  // Daily Essentials (20 products)
  {
    id: "de-001",
    name: "Portable Cutlery Set with Case",
    category: "daily-essentials",
    price: 12.99,
    originalPrice: 19.99,
    image: "/portable-stainless-steel-cutlery-set-with-travel-c.jpg",
    rating: 4.8,
    reviews: 2341,
    inStock: true,
    description: "Eco-friendly stainless steel cutlery set perfect for travel, office, or outdoor dining.",
    features: [
      "Food-grade stainless steel",
      "Portable carrying case",
      "Dishwasher safe",
      "Includes fork, spoon, knife, chopsticks",
    ],
    specifications: { Material: "Stainless Steel", Weight: "180g", Size: "19cm x 6cm" },
  },
  {
    id: "de-002",
    name: "Silicone Food Storage Containers Set",
    category: "daily-essentials",
    price: 24.99,
    originalPrice: 34.99,
    image: "/colorful-silicone-collapsible-food-storage-contain.jpg",
    rating: 4.7,
    reviews: 1876,
    inStock: true,
    description: "Collapsible silicone containers that save space and keep food fresh.",
    features: ["BPA-free silicone", "Microwave & freezer safe", "Collapsible design", "Set of 4 sizes"],
    specifications: { Material: "Food-grade Silicone", Capacity: "350ml-1200ml", Temperature: "-40°C to 230°C" },
  },
  {
    id: "de-003",
    name: "Multi-Function Space-Saving Hangers",
    category: "daily-essentials",
    price: 15.99,
    image: "/modern-multi-layer-clothing-hangers-organizer.jpg",
    rating: 4.6,
    reviews: 3421,
    inStock: true,
    description: "5-in-1 hangers that maximize closet space and keep clothes organized.",
    features: ["Holds 5 garments", "Non-slip design", "Durable plastic", "360° rotating hook"],
    specifications: { Material: "ABS Plastic", Dimensions: "42cm x 18cm", "Load Capacity": "15kg" },
  },
  {
    id: "de-004",
    name: "Compressed Travel Towel Set",
    category: "daily-essentials",
    price: 9.99,
    image: "/compressed-cotton-travel-towels-in-packaging.jpg",
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    description: "Ultra-compact towels that expand when wet, perfect for travel.",
    features: ["100% cotton", "Expands to full size", "Quick-dry", "Pack of 10"],
    specifications: { Material: "100% Cotton", "Compressed Size": "3cm x 3cm", "Expanded Size": "30cm x 30cm" },
  },
  {
    id: "de-005",
    name: "Travel Organizer Bag Set",
    category: "daily-essentials",
    price: 18.99,
    originalPrice: 29.99,
    image: "/travel-packing-cubes-organizer-set.jpg",
    rating: 4.9,
    reviews: 4567,
    inStock: true,
    description: "Complete packing cube set to organize luggage efficiently.",
    features: ["7-piece set", "Waterproof material", "Mesh top panel", "Multiple sizes"],
    specifications: { Material: "Nylon", Set: "7 pieces", Colors: "Multiple options" },
  },
  {
    id: "de-006",
    name: "Mini Robot Vacuum Cleaner",
    category: "daily-essentials",
    price: 49.99,
    originalPrice: 79.99,
    image: "/compact-robot-vacuum-cleaner-for-home.jpg",
    rating: 4.4,
    reviews: 892,
    inStock: true,
    description: "Compact automatic vacuum for daily floor cleaning.",
    features: ["Auto-charging", "Low noise", "Smart navigation", "HEPA filter"],
    specifications: { "Battery Life": "90 minutes", "Noise Level": "55dB", Diameter: "28cm" },
  },
  {
    id: "de-007",
    name: "Electric Milk Frother",
    category: "daily-essentials",
    price: 14.99,
    image: "/handheld-electric-milk-frother-coffee-tool.jpg",
    rating: 4.7,
    reviews: 2109,
    inStock: true,
    description: "Create café-quality foam at home in seconds.",
    features: ["USB rechargeable", "Stainless steel whisk", "Quiet operation", "Easy to clean"],
    specifications: { Power: "3W", "Battery Capacity": "800mAh", Material: "Stainless Steel" },
  },
  {
    id: "de-008",
    name: "Adjustable Laptop Stand",
    category: "daily-essentials",
    price: 22.99,
    image: "/ergonomic-adjustable-aluminum-laptop-stand.jpg",
    rating: 4.8,
    reviews: 3456,
    inStock: true,
    description: "Ergonomic stand improves posture and cooling.",
    features: ["6 height levels", "Aluminum alloy", "Foldable design", 'Supports up to 17" laptops'],
    specifications: { Material: "Aluminum Alloy", Weight: "850g", "Max Load": "10kg" },
  },
  {
    id: "de-009",
    name: "LED Desk Lamp with Wireless Charging",
    category: "daily-essentials",
    price: 34.99,
    originalPrice: 49.99,
    image: "/modern-led-desk-lamp-with-wireless-phone-charging.jpg",
    rating: 4.6,
    reviews: 1567,
    inStock: true,
    description: "Multi-functional lamp with phone charging and adjustable brightness.",
    features: ["Wireless charging pad", "3 color modes", "Touch control", "USB port"],
    specifications: { Power: "15W", "Color Temperature": "3000K-6000K", "Charging Output": "10W" },
  },
  {
    id: "de-010",
    name: "Insulated Lunch Box",
    category: "daily-essentials",
    price: 16.99,
    image: "/insulated-stainless-steel-lunch-box-container.jpg",
    rating: 4.5,
    reviews: 987,
    inStock: true,
    description: "Keep meals hot or cold for hours with this premium lunch box.",
    features: ["Double-wall insulation", "Leak-proof", "Stainless steel", "2 compartments"],
    specifications: { Capacity: "1.2L", Material: "Stainless Steel 304", Dimensions: "20cm x 15cm x 8cm" },
  },
  {
    id: "de-011",
    name: "Digital Kitchen Scale",
    category: "daily-essentials",
    price: 11.99,
    image: "/digital-kitchen-food-scale-with-lcd-display.jpg",
    rating: 4.7,
    reviews: 2345,
    inStock: true,
    description: "Precise measurements for cooking and baking.",
    features: ["0.1g precision", "Tare function", "LCD display", "Auto shut-off"],
    specifications: { Capacity: "5kg", Accuracy: "0.1g", Power: "2x AAA batteries" },
  },
  {
    id: "de-012",
    name: "Bamboo Drawer Organizers",
    category: "daily-essentials",
    price: 19.99,
    image: "/bamboo-drawer-divider-organizer-set.jpg",
    rating: 4.8,
    reviews: 1432,
    inStock: true,
    description: "Eco-friendly organizers for kitchen and office drawers.",
    features: ["Natural bamboo", "Adjustable dividers", "Set of 6", "Easy to clean"],
    specifications: { Material: "Bamboo", Sizes: "Various", Finish: "Natural" },
  },
  {
    id: "de-013",
    name: "Electric Wine Opener Set",
    category: "daily-essentials",
    price: 27.99,
    image: "/automatic-electric-wine-bottle-opener-set.jpg",
    rating: 4.6,
    reviews: 876,
    inStock: true,
    description: "Open wine bottles effortlessly with this electric opener.",
    features: ["Opens 30+ bottles per charge", "Foil cutter included", "LED indicator", "Elegant design"],
    specifications: {
      Power: "Rechargeable battery",
      Material: "Stainless Steel",
      Includes: "Opener, foil cutter, pourer",
    },
  },
  {
    id: "de-014",
    name: "Magnetic Knife Holder",
    category: "daily-essentials",
    price: 13.99,
    image: "/wall-mounted-magnetic-knife-holder-strip.jpg",
    rating: 4.7,
    reviews: 1654,
    inStock: true,
    description: "Space-saving magnetic strip for kitchen knives.",
    features: ["Strong magnets", "Easy installation", "Bamboo or stainless steel", "40cm length"],
    specifications: { Length: "40cm", Material: "Bamboo/Stainless Steel", "Mounting Type": "Wall-mounted" },
  },
  {
    id: "de-015",
    name: "Shower Caddy Organizer",
    category: "daily-essentials",
    price: 21.99,
    image: "/rust-proof-shower-caddy-organizer-shelves.jpg",
    rating: 4.5,
    reviews: 1098,
    inStock: true,
    description: "Rust-proof shower organizer with multiple shelves.",
    features: ["Stainless steel", "Adjustable height", "4 shelves", "No drilling required"],
    specifications: { Material: "Stainless Steel 304", Height: "Adjustable 180-300cm", Shelves: "4 tiers" },
  },
  {
    id: "de-016",
    name: "Automatic Soap Dispenser",
    category: "daily-essentials",
    price: 17.99,
    image: "/automatic-touchless-soap-dispenser.jpg",
    rating: 4.6,
    reviews: 2187,
    inStock: true,
    description: "Touchless soap dispenser for hygiene and convenience.",
    features: ["Infrared sensor", "Adjustable volume", "Waterproof", "USB rechargeable"],
    specifications: { Capacity: "350ml", Power: "USB rechargeable", Material: "ABS Plastic" },
  },
  {
    id: "de-017",
    name: "Cable Management Box",
    category: "daily-essentials",
    price: 14.99,
    image: "/cable-organizer-management-box.jpg",
    rating: 4.4,
    reviews: 765,
    inStock: true,
    description: "Hide and organize messy cables and power strips.",
    features: ["Large capacity", "Heat dissipation holes", "Non-slip base", "Modern design"],
    specifications: { Dimensions: "32cm x 13cm x 13cm", Material: "ABS Plastic", Color: "White/Black" },
  },
  {
    id: "de-018",
    name: "Reusable Silicone Food Bags",
    category: "daily-essentials",
    price: 18.99,
    image: "/reusable-silicone-food-storage-bags-set.jpg",
    rating: 4.8,
    reviews: 3210,
    inStock: true,
    description: "Eco-friendly alternative to plastic bags.",
    features: ["Set of 6", "Leak-proof seal", "Microwave safe", "Easy to clean"],
    specifications: { Material: "Food-grade Silicone", Sizes: "3 sizes included", Temperature: "-40°C to 230°C" },
  },
  {
    id: "de-019",
    name: "UV Phone Sanitizer Box",
    category: "daily-essentials",
    price: 29.99,
    originalPrice: 44.99,
    image: "/uv-phone-sanitizer-wireless-charger-box.jpg",
    rating: 4.5,
    reviews: 1432,
    inStock: true,
    description: "Sanitize your phone and small items with UV-C light.",
    features: ["UV-C sterilization", "Wireless charging", "Aromatherapy function", "5-minute cycle"],
    specifications: { Power: "10W", "UV Wavelength": "253.7nm", Compatibility: 'Phones up to 6.5"' },
  },
  {
    id: "de-020",
    name: "Collapsible Laundry Basket",
    category: "daily-essentials",
    price: 16.99,
    image: "/collapsible-laundry-basket-hamper.jpg",
    rating: 4.6,
    reviews: 1876,
    inStock: true,
    description: "Space-saving laundry basket that folds flat.",
    features: ["Collapsible design", "Reinforced handles", "Waterproof lining", "Large capacity"],
    specifications: { Capacity: "60L", Material: "Oxford Fabric", Dimensions: "40cm x 30cm x 50cm" },
  },

  // Men's Fashion (20 products)
  {
    id: "mf-001",
    name: "Quick-Dry Performance Polo Shirt",
    category: "mens-fashion",
    price: 24.99,
    originalPrice: 39.99,
    image: "/mens-quick-dry-performance-polo-shirt.jpg",
    rating: 4.7,
    reviews: 1543,
    inStock: true,
    description: "Breathable polo perfect for sports and casual wear.",
    features: ["Moisture-wicking fabric", "UV protection", "Anti-odor technology", "Multiple colors"],
    specifications: { Material: "95% Polyester, 5% Spandex", Sizes: "S-3XL", Care: "Machine washable" },
  },
  {
    id: "mf-002",
    name: "Slim Fit Business Casual Pants",
    category: "mens-fashion",
    price: 34.99,
    originalPrice: 54.99,
    image: "/mens-slim-fit-business-casual-pants.jpg",
    rating: 4.6,
    reviews: 2341,
    inStock: true,
    description: "Versatile pants for office and casual occasions.",
    features: ["Stretch fabric", "Wrinkle-resistant", "4-way stretch", "Multiple pockets"],
    specifications: { Material: "68% Polyester, 29% Rayon, 3% Spandex", Sizes: "28-40", Colors: "6 options" },
  },
  {
    id: "mf-003",
    name: "Lightweight Down Jacket",
    category: "mens-fashion",
    price: 59.99,
    originalPrice: 99.99,
    image: "/mens-lightweight-packable-down-jacket.jpg",
    rating: 4.8,
    reviews: 3210,
    inStock: true,
    description: "Packable down jacket for cold weather.",
    features: ["90% down fill", "Water-resistant", "Packable design", "Lightweight"],
    specifications: { Fill: "90% Duck Down", Weight: "350g", Sizes: "S-3XL" },
  },
  {
    id: "mf-004",
    name: "Premium Cotton Dress Socks Set",
    category: "mens-fashion",
    price: 19.99,
    image: "/mens-premium-cotton-dress-socks-set.jpg",
    rating: 4.5,
    reviews: 987,
    inStock: true,
    description: "Comfortable dress socks for business and formal wear.",
    features: ["Breathable cotton", "Reinforced heel and toe", "Set of 6 pairs", "Multiple patterns"],
    specifications: {
      Material: "80% Cotton, 15% Polyester, 5% Spandex",
      Sizes: "One size fits most",
      Package: "6 pairs",
    },
  },
  {
    id: "mf-005",
    name: "Classic Denim Shirt",
    category: "mens-fashion",
    price: 29.99,
    image: "/mens-classic-denim-button-down-shirt.jpg",
    rating: 4.7,
    reviews: 1654,
    inStock: true,
    description: "Timeless denim shirt for casual style.",
    features: ["100% cotton denim", "Button-down collar", "Chest pockets", "Regular fit"],
    specifications: { Material: "100% Cotton", Weight: "8oz denim", Sizes: "S-XXL" },
  },
  {
    id: "mf-006",
    name: "Athletic Performance Shorts",
    category: "mens-fashion",
    price: 22.99,
    image: "/mens-athletic-performance-running-shorts.jpg",
    rating: 4.6,
    reviews: 2109,
    inStock: true,
    description: "Comfortable shorts for workouts and running.",
    features: ["Quick-dry fabric", "Zippered pockets", "Elastic waistband", "Reflective details"],
    specifications: { Material: "100% Polyester", Inseam: "7 inches", Sizes: "S-XXL" },
  },
  {
    id: "mf-007",
    name: "Leather Belt with Automatic Buckle",
    category: "mens-fashion",
    price: 26.99,
    image: "/mens-leather-belt-automatic-buckle.jpg",
    rating: 4.8,
    reviews: 1876,
    inStock: true,
    description: "Premium leather belt with modern automatic buckle.",
    features: ["Genuine leather", "Automatic buckle", "Adjustable length", "Gift box included"],
    specifications: { Material: "Genuine Leather", Width: "3.5cm", Length: "Adjustable 110-130cm" },
  },
  {
    id: "mf-008",
    name: "Merino Wool Sweater",
    category: "mens-fashion",
    price: 44.99,
    originalPrice: 69.99,
    image: "/mens-merino-wool-crew-neck-sweater.jpg",
    rating: 4.7,
    reviews: 1234,
    inStock: true,
    description: "Soft merino wool sweater for layering.",
    features: ["100% merino wool", "Temperature regulating", "Odor-resistant", "Classic fit"],
    specifications: { Material: "100% Merino Wool", Weight: "Midweight", Sizes: "S-XXL" },
  },
  {
    id: "mf-009",
    name: "Stretch Jeans Slim Fit",
    category: "mens-fashion",
    price: 39.99,
    originalPrice: 59.99,
    image: "/mens-stretch-slim-fit-jeans.jpg",
    rating: 4.6,
    reviews: 3456,
    inStock: true,
    description: "Comfortable stretch jeans with modern fit.",
    features: ["Stretch denim", "Fade-resistant", "5-pocket design", "Multiple washes"],
    specifications: { Material: "79% Cotton, 20% Polyester, 1% Spandex", Fit: "Slim", Sizes: "28-40" },
  },
  {
    id: "mf-010",
    name: "Windbreaker Jacket",
    category: "mens-fashion",
    price: 42.99,
    image: "/mens-windbreaker-jacket-lightweight.jpg",
    rating: 4.5,
    reviews: 1567,
    inStock: true,
    description: "Lightweight jacket for wind and light rain protection.",
    features: ["Water-resistant", "Packable hood", "Zippered pockets", "Adjustable cuffs"],
    specifications: { Material: "100% Nylon", Weight: "280g", Sizes: "S-XXL" },
  },
  {
    id: "mf-011",
    name: "Oxford Dress Shirt",
    category: "mens-fashion",
    price: 32.99,
    image: "/mens-oxford-dress-shirt-button-down.jpg",
    rating: 4.7,
    reviews: 2187,
    inStock: true,
    description: "Classic oxford shirt for business and formal occasions.",
    features: ["100% cotton oxford", "Button-down collar", "Wrinkle-resistant", "Regular fit"],
    specifications: { Material: "100% Cotton", Weave: "Oxford", Sizes: "S-XXL" },
  },
  {
    id: "mf-012",
    name: "Cargo Shorts with Multiple Pockets",
    category: "mens-fashion",
    price: 27.99,
    image: "/mens-cargo-shorts-multiple-pockets.jpg",
    rating: 4.4,
    reviews: 876,
    inStock: true,
    description: "Functional cargo shorts for outdoor activities.",
    features: ["8 pockets", "Durable fabric", "Belt included", "Relaxed fit"],
    specifications: { Material: "100% Cotton", Inseam: "11 inches", Sizes: "30-42" },
  },
  {
    id: "mf-013",
    name: "Thermal Base Layer Set",
    category: "mens-fashion",
    price: 34.99,
    image: "/mens-thermal-base-layer-set.jpg",
    rating: 4.8,
    reviews: 1432,
    inStock: true,
    description: "Warm base layer for cold weather activities.",
    features: ["Fleece-lined", "Moisture-wicking", "Top and bottom set", "Stretchy fabric"],
    specifications: { Material: "92% Polyester, 8% Spandex", Weight: "Heavyweight", Sizes: "S-XXL" },
  },
  {
    id: "mf-014",
    name: "Casual Henley Shirt",
    category: "mens-fashion",
    price: 21.99,
    image: "/mens-casual-henley-long-sleeve-shirt.jpg",
    rating: 4.6,
    reviews: 1654,
    inStock: true,
    description: "Comfortable henley for casual everyday wear.",
    features: ["Soft cotton blend", "Button placket", "Long sleeves", "Multiple colors"],
    specifications: { Material: "60% Cotton, 40% Polyester", Fit: "Regular", Sizes: "S-XXL" },
  },
  {
    id: "mf-015",
    name: "Swim Trunks Quick-Dry",
    category: "mens-fashion",
    price: 24.99,
    image: "/mens-swim-trunks-quick-dry.jpg",
    rating: 4.5,
    reviews: 987,
    inStock: true,
    description: "Quick-drying swim trunks for beach and pool.",
    features: ["Quick-dry fabric", "Mesh lining", "Elastic waistband", "Side pockets"],
    specifications: { Material: "100% Polyester", Inseam: "7 inches", Sizes: "S-XXL" },
  },
  {
    id: "mf-016",
    name: "Flannel Plaid Shirt",
    category: "mens-fashion",
    price: 28.99,
    image: "/mens-flannel-plaid-button-up-shirt.jpg",
    rating: 4.7,
    reviews: 2345,
    inStock: true,
    description: "Warm flannel shirt with classic plaid pattern.",
    features: ["100% cotton flannel", "Button-down collar", "Chest pockets", "Soft brushed finish"],
    specifications: { Material: "100% Cotton", Weight: "Midweight", Sizes: "S-XXL" },
  },
  {
    id: "mf-017",
    name: "Compression Athletic Shirt",
    category: "mens-fashion",
    price: 26.99,
    image: "/mens-compression-athletic-shirt.jpg",
    rating: 4.6,
    reviews: 1765,
    inStock: true,
    description: "Compression shirt for enhanced athletic performance.",
    features: ["Compression fit", "Moisture-wicking", "Flatlock seams", "UV protection"],
    specifications: { Material: "87% Polyester, 13% Spandex", Fit: "Compression", Sizes: "S-XXL" },
  },
  {
    id: "mf-018",
    name: "Chino Shorts Classic Fit",
    category: "mens-fashion",
    price: 29.99,
    image: "/mens-chino-shorts-classic-fit.jpg",
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    description: "Versatile chino shorts for casual summer wear.",
    features: ["Cotton twill", "Classic fit", "Multiple pockets", "Belt loops"],
    specifications: { Material: "100% Cotton", Inseam: "9 inches", Sizes: "30-42" },
  },
  {
    id: "mf-019",
    name: "Hooded Sweatshirt",
    category: "mens-fashion",
    price: 36.99,
    image: "/mens-hooded-sweatshirt-pullover.jpg",
    rating: 4.7,
    reviews: 2876,
    inStock: true,
    description: "Comfortable hoodie for casual wear and layering.",
    features: ["Fleece-lined", "Kangaroo pocket", "Adjustable hood", "Ribbed cuffs"],
    specifications: { Material: "80% Cotton, 20% Polyester", Weight: "Heavyweight", Sizes: "S-XXL" },
  },
  {
    id: "mf-020",
    name: "Performance Track Pants",
    category: "mens-fashion",
    price: 31.99,
    image: "/mens-performance-track-pants.jpg",
    rating: 4.6,
    reviews: 1543,
    inStock: true,
    description: "Athletic pants for training and casual wear.",
    features: ["Moisture-wicking", "Zippered pockets", "Elastic waistband", "Tapered fit"],
    specifications: { Material: "100% Polyester", Fit: "Tapered", Sizes: "S-XXL" },
  },

  // Women's Fashion (20 products)
  {
    id: "wf-001",
    name: "Flowy Chiffon Maxi Dress",
    category: "womens-fashion",
    price: 39.99,
    originalPrice: 59.99,
    image: "/womens-flowy-chiffon-maxi-dress.jpg",
    rating: 4.8,
    reviews: 3210,
    inStock: true,
    description: "Elegant maxi dress perfect for special occasions.",
    features: ["Lightweight chiffon", "Flowy silhouette", "Adjustable straps", "Lined"],
    specifications: { Material: "100% Polyester Chiffon", Length: "Maxi", Sizes: "XS-XXL" },
  },
  {
    id: "wf-002",
    name: "High-Waist Skinny Jeans",
    category: "womens-fashion",
    price: 42.99,
    originalPrice: 64.99,
    image: "/womens-high-waist-skinny-jeans.jpg",
    rating: 4.7,
    reviews: 4567,
    inStock: true,
    description: "Flattering high-waist jeans with stretch comfort.",
    features: ["High-rise waist", "4-way stretch", "Slimming fit", "Multiple washes"],
    specifications: { Material: "76% Cotton, 22% Polyester, 2% Spandex", Rise: "High", Sizes: "24-34" },
  },
  {
    id: "wf-003",
    name: "UV Protection Cardigan",
    category: "womens-fashion",
    price: 27.99,
    image: "/womens-uv-protection-cardigan.jpg",
    rating: 4.6,
    reviews: 1876,
    inStock: true,
    description: "Lightweight cardigan with sun protection.",
    features: ["UPF 50+ protection", "Breathable fabric", "Long sleeves", "Multiple colors"],
    specifications: { Material: "95% Polyester, 5% Spandex", Protection: "UPF 50+", Sizes: "S-XL" },
  },
  {
    id: "wf-004",
    name: "Seamless Sports Bra",
    category: "womens-fashion",
    price: 19.99,
    image: "/womens-seamless-sports-bra.jpg",
    rating: 4.5,
    reviews: 2341,
    inStock: true,
    description: "Comfortable sports bra for medium-impact activities.",
    features: ["Seamless design", "Removable pads", "Moisture-wicking", "Medium support"],
    specifications: { Material: "92% Nylon, 8% Spandex", Support: "Medium", Sizes: "XS-XL" },
  },
  {
    id: "wf-005",
    name: "Pleated Midi Skirt",
    category: "womens-fashion",
    price: 32.99,
    image: "/womens-pleated-midi-skirt.jpg",
    rating: 4.7,
    reviews: 1654,
    inStock: true,
    description: "Elegant pleated skirt for office and casual wear.",
    features: ["Accordion pleats", "Elastic waistband", "Midi length", "Flowy fabric"],
    specifications: { Material: "100% Polyester", Length: "Midi (knee-length)", Sizes: "XS-XL" },
  },
  {
    id: "wf-006",
    name: "Casual T-Shirt 3-Pack",
    category: "womens-fashion",
    price: 24.99,
    image: "/womens-casual-t-shirt-3-pack.jpg",
    rating: 4.6,
    reviews: 3456,
    inStock: true,
    description: "Essential basic tees for everyday wear.",
    features: ["Soft cotton blend", "Crew neck", "Pack of 3", "Multiple colors"],
    specifications: { Material: "95% Cotton, 5% Spandex", Fit: "Regular", Sizes: "XS-XXL" },
  },
  {
    id: "wf-007",
    name: "Yoga Leggings High-Waist",
    category: "womens-fashion",
    price: 29.99,
    originalPrice: 44.99,
    image: "/womens-yoga-leggings-high-waist.jpg",
    rating: 4.8,
    reviews: 5432,
    inStock: true,
    description: "Premium leggings for yoga and fitness.",
    features: ["High-waist design", "Squat-proof", "Hidden pocket", "4-way stretch"],
    specifications: { Material: "87% Nylon, 13% Spandex", Compression: "Medium", Sizes: "XS-XXL" },
  },
  {
    id: "wf-008",
    name: "Knit Sweater Pullover",
    category: "womens-fashion",
    price: 36.99,
    image: "/womens-knit-sweater-pullover.jpg",
    rating: 4.7,
    reviews: 1987,
    inStock: true,
    description: "Cozy knit sweater for cool weather.",
    features: ["Soft knit fabric", "Crew neck", "Ribbed cuffs", "Relaxed fit"],
    specifications: { Material: "60% Cotton, 40% Acrylic", Weight: "Midweight", Sizes: "S-XL" },
  },
  {
    id: "wf-009",
    name: "Wide-Leg Palazzo Pants",
    category: "womens-fashion",
    price: 34.99,
    image: "/womens-wide-leg-palazzo-pants.jpg",
    rating: 4.6,
    reviews: 1432,
    inStock: true,
    description: "Comfortable wide-leg pants with elegant drape.",
    features: ["Flowy fabric", "Elastic waistband", "Wide leg", "Wrinkle-resistant"],
    specifications: { Material: "95% Polyester, 5% Spandex", Fit: "Wide leg", Sizes: "XS-XL" },
  },
  {
    id: "wf-010",
    name: "Denim Jacket Classic",
    category: "womens-fashion",
    price: 44.99,
    originalPrice: 69.99,
    image: "/womens-denim-jacket-classic.jpg",
    rating: 4.7,
    reviews: 2876,
    inStock: true,
    description: "Timeless denim jacket for layering.",
    features: ["100% cotton denim", "Button closure", "Chest pockets", "Classic fit"],
    specifications: { Material: "100% Cotton", Weight: "12oz denim", Sizes: "XS-XL" },
  },
  {
    id: "wf-011",
    name: "Silk Blend Camisole",
    category: "womens-fashion",
    price: 22.99,
    image: "/womens-silk-blend-camisole.jpg",
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    description: "Luxurious camisole for layering or standalone wear.",
    features: ["Silk blend fabric", "Adjustable straps", "V-neck", "Multiple colors"],
    specifications: { Material: "95% Polyester, 5% Silk", Fit: "Regular", Sizes: "XS-XL" },
  },
  {
    id: "wf-012",
    name: "Athletic Shorts with Liner",
    category: "womens-fashion",
    price: 21.99,
    image: "/womens-athletic-shorts-with-liner.jpg",
    rating: 4.6,
    reviews: 1765,
    inStock: true,
    description: "Comfortable shorts for running and workouts.",
    features: ["Built-in liner", "Moisture-wicking", "Side pockets", "Reflective details"],
    specifications: { Material: "100% Polyester", Inseam: "3 inches", Sizes: "XS-XL" },
  },
  {
    id: "wf-013",
    name: "Wrap Blouse Elegant",
    category: "womens-fashion",
    price: 31.99,
    image: "/womens-wrap-blouse-elegant.jpg",
    rating: 4.7,
    reviews: 1543,
    inStock: true,
    description: "Flattering wrap blouse for office and events.",
    features: ["Wrap design", "V-neckline", "Tie waist", "Flowy sleeves"],
    specifications: { Material: "100% Polyester", Fit: "Wrap style", Sizes: "XS-XXL" },
  },
  {
    id: "wf-014",
    name: "Linen Blend Shorts",
    category: "womens-fashion",
    price: 26.99,
    image: "/womens-linen-blend-shorts.jpg",
    rating: 4.5,
    reviews: 987,
    inStock: true,
    description: "Breathable linen shorts for summer comfort.",
    features: ["Linen blend", "Elastic waistband", "Side pockets", "Relaxed fit"],
    specifications: { Material: "55% Linen, 45% Cotton", Inseam: "5 inches", Sizes: "XS-XL" },
  },
  {
    id: "wf-015",
    name: "Turtleneck Sweater",
    category: "womens-fashion",
    price: 33.99,
    image: "/womens-turtleneck-sweater.jpg",
    rating: 4.6,
    reviews: 1654,
    inStock: true,
    description: "Classic turtleneck for layering and warmth.",
    features: ["Ribbed knit", "Turtleneck", "Slim fit", "Soft fabric"],
    specifications: { Material: "70% Viscose, 30% Nylon", Fit: "Slim", Sizes: "XS-XL" },
  },
  {
    id: "wf-016",
    name: "Printed Maxi Skirt",
    category: "womens-fashion",
    price: 37.99,
    image: "/womens-printed-maxi-skirt.jpg",
    rating: 4.7,
    reviews: 2109,
    inStock: true,
    description: "Vibrant printed skirt for summer style.",
    features: ["Floral print", "Elastic waistband", "Maxi length", "Flowy fabric"],
    specifications: { Material: "100% Rayon", Length: "Maxi", Sizes: "XS-XL" },
  },
  {
    id: "wf-017",
    name: "Cropped Hoodie",
    category: "womens-fashion",
    price: 28.99,
    image: "/womens-cropped-hoodie.jpg",
    rating: 4.5,
    reviews: 1876,
    inStock: true,
    description: "Trendy cropped hoodie for casual wear.",
    features: ["Cropped length", "Drawstring hood", "Kangaroo pocket", "Soft fleece"],
    specifications: { Material: "80% Cotton, 20% Polyester", Fit: "Cropped", Sizes: "XS-XL" },
  },
  {
    id: "wf-018",
    name: "Pencil Skirt Office",
    category: "womens-fashion",
    price: 29.99,
    image: "/womens-pencil-skirt-office.jpg",
    rating: 4.6,
    reviews: 1432,
    inStock: true,
    description: "Professional pencil skirt for office wear.",
    features: ["Stretch fabric", "Back slit", "Knee length", "Wrinkle-resistant"],
    specifications: { Material: "68% Polyester, 29% Rayon, 3% Spandex", Length: "Knee", Sizes: "XS-XXL" },
  },
  {
    id: "wf-019",
    name: "Lace Trim Camisole",
    category: "womens-fashion",
    price: 18.99,
    image: "/womens-lace-trim-camisole.jpg",
    rating: 4.5,
    reviews: 2345,
    inStock: true,
    description: "Delicate camisole with lace detailing.",
    features: ["Lace trim", "Adjustable straps", "Soft fabric", "Multiple colors"],
    specifications: { Material: "95% Rayon, 5% Spandex", Fit: "Regular", Sizes: "XS-XL" },
  },
  {
    id: "wf-020",
    name: "Jogger Pants Casual",
    category: "womens-fashion",
    price: 32.99,
    image: "/womens-jogger-pants-casual.jpg",
    rating: 4.7,
    reviews: 2876,
    inStock: true,
    description: "Comfortable joggers for lounging and casual wear.",
    features: ["Soft fleece", "Elastic waistband", "Tapered leg", "Side pockets"],
    specifications: { Material: "80% Cotton, 20% Polyester", Fit: "Tapered", Sizes: "XS-XXL" },
  },

  // Outdoor & Camping (20 products)
  {
    id: "oc-001",
    name: "Instant Pop-Up Tent 4-Person",
    category: "outdoor-camping",
    price: 89.99,
    originalPrice: 129.99,
    image: "/instant-pop-up-tent-4-person.jpg",
    rating: 4.7,
    reviews: 1543,
    inStock: true,
    description: "Quick-setup tent perfect for camping trips.",
    features: ["Sets up in 60 seconds", "Waterproof coating", "Ventilation windows", "Carry bag included"],
    specifications: { Capacity: "4 persons", Dimensions: "240cm x 210cm x 130cm", Weight: "4.5kg" },
  },
  {
    id: "oc-002",
    name: "Mummy Sleeping Bag -10°C",
    category: "outdoor-camping",
    price: 54.99,
    originalPrice: 79.99,
    image: "/mummy-sleeping-bag-cold-weather.jpg",
    rating: 4.8,
    reviews: 2341,
    inStock: true,
    description: "Warm sleeping bag for cold weather camping.",
    features: ["Temperature rated -10°C", "Mummy shape", "Compression sack", "Water-resistant"],
    specifications: { "Temperature Rating": "-10°C", Fill: "Synthetic", Weight: "1.8kg" },
  },
  {
    id: "oc-003",
    name: "Waterproof Picnic Blanket",
    category: "outdoor-camping",
    price: 24.99,
    image: "/waterproof-picnic-blanket-outdoor.jpg",
    rating: 4.6,
    reviews: 1876,
    inStock: true,
    description: "Large waterproof blanket for picnics and beach.",
    features: ["Waterproof backing", "Folds compactly", "Carrying handle", "Machine washable"],
    specifications: { Size: "200cm x 200cm", Material: "Polyester with waterproof backing", Weight: "800g" },
  },
  {
    id: "oc-004",
    name: "Portable Folding Chair",
    category: "outdoor-camping",
    price: 32.99,
    image: "/portable-folding-camping-chair.jpg",
    rating: 4.7,
    reviews: 1654,
    inStock: true,
    description: "Lightweight chair for camping and outdoor events.",
    features: ["Aluminum frame", "Cup holder", "Carry bag", "Supports 150kg"],
    specifications: { Material: "Aluminum + Oxford fabric", Weight: "2.2kg", "Load Capacity": "150kg" },
  },
  {
    id: "oc-005",
    name: "LED Camping Lantern Rechargeable",
    category: "outdoor-camping",
    price: 27.99,
    image: "/led-camping-lantern-rechargeable.jpg",
    rating: 4.8,
    reviews: 2109,
    inStock: true,
    description: "Bright LED lantern with multiple lighting modes.",
    features: ["1000 lumens", "USB rechargeable", "3 light modes", "Power bank function"],
    specifications: { Brightness: "1000 lumens", "Battery Life": "12-48 hours", "Charging Time": "4 hours" },
  },
  {
    id: "oc-006",
    name: "Portable Charcoal Grill",
    category: "outdoor-camping",
    price: 44.99,
    image: "/portable-charcoal-grill-camping.jpg",
    rating: 4.5,
    reviews: 987,
    inStock: true,
    description: "Compact grill for outdoor cooking.",
    features: ["Foldable design", "Stainless steel", "Adjustable height", "Carry case included"],
    specifications: { Material: "Stainless Steel", "Cooking Area": "35cm x 27cm", Weight: "3.5kg" },
  },
  {
    id: "oc-007",
    name: "Trekking Poles Pair",
    category: "outdoor-camping",
    price: 29.99,
    originalPrice: 44.99,
    image: "/trekking-poles-adjustable-pair.jpg",
    rating: 4.7,
    reviews: 1432,
    inStock: true,
    description: "Adjustable poles for hiking and trekking.",
    features: ["Adjustable length", "Anti-shock system", "Cork grips", "Tungsten tips"],
    specifications: { Material: "Aluminum alloy", "Length Range": "65-135cm", Weight: "280g each" },
  },
  {
    id: "oc-008",
    name: "Camping Cookware Set",
    category: "outdoor-camping",
    price: 39.99,
    image: "/camping-cookware-set-portable.jpg",
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    description: "Complete cookware set for outdoor cooking.",
    features: ["11-piece set", "Non-stick coating", "Nesting design", "Mesh carry bag"],
    specifications: { Pieces: "11", Material: "Aluminum with non-stick coating", Weight: "1.2kg" },
  },
  {
    id: "oc-009",
    name: "Inflatable Camping Pillow",
    category: "outdoor-camping",
    price: 14.99,
    image: "/inflatable-camping-pillow-compact.jpg",
    rating: 4.5,
    reviews: 876,
    inStock: true,
    description: "Compact pillow for comfortable camping sleep.",
    features: ["Inflates in seconds", "Soft fabric cover", "Compact when deflated", "Adjustable firmness"],
    specifications: { Material: "TPU + Polyester", "Inflated Size": "40cm x 30cm x 12cm", Weight: "85g" },
  },
  {
    id: "oc-010",
    name: "Waterproof Dry Bag 20L",
    category: "outdoor-camping",
    price: 19.99,
    image: "/waterproof-dry-bag-20l.jpg",
    rating: 4.7,
    reviews: 1765,
    inStock: true,
    description: "Keep gear dry during water activities.",
    features: ["100% waterproof", "Roll-top closure", "Shoulder strap", "Durable PVC"],
    specifications: { Capacity: "20L", Material: "PVC tarpaulin", Waterproof: "IPX6" },
  },
  {
    id: "oc-011",
    name: "Camping Hammock with Mosquito Net",
    category: "outdoor-camping",
    price: 42.99,
    image: "/camping-hammock-with-mosquito-net.jpg",
    rating: 4.8,
    reviews: 1543,
    inStock: true,
    description: "Comfortable hammock with built-in bug protection.",
    features: ["Mosquito net included", "Supports 200kg", "Easy setup", "Carry bag"],
    specifications: { Material: "Parachute nylon", Dimensions: "290cm x 140cm", "Load Capacity": "200kg" },
  },
  {
    id: "oc-012",
    name: "Portable Water Filter",
    category: "outdoor-camping",
    price: 34.99,
    image: "/portable-water-filter-camping.jpg",
    rating: 4.6,
    reviews: 987,
    inStock: true,
    description: "Purify water from natural sources safely.",
    features: ["Filters 99.99% bacteria", "1000L capacity", "Lightweight", "Fast flow rate"],
    specifications: { Capacity: "1000 liters", "Flow Rate": "1.7L/min", Weight: "56g" },
  },
  {
    id: "oc-013",
    name: "Camping Axe Multi-Tool",
    category: "outdoor-camping",
    price: 36.99,
    image: "/camping-axe-multi-tool.jpg",
    rating: 4.7,
    reviews: 1234,
    inStock: true,
    description: "Versatile axe for camping and survival.",
    features: ["Stainless steel blade", "Hammer head", "Nylon sheath", "Ergonomic handle"],
    specifications: { Material: "Stainless Steel + Fiberglass", Weight: "680g", Length: "38cm" },
  },
  {
    id: "oc-014",
    name: "Insulated Cooler Bag 30L",
    category: "outdoor-camping",
    price: 29.99,
    image: "/insulated-cooler-bag-30l.jpg",
    rating: 4.5,
    reviews: 1432,
    inStock: true,
    description: "Keep food and drinks cold for hours.",
    features: ["30L capacity", "Thick insulation", "Multiple pockets", "Shoulder strap"],
    specifications: { Capacity: "30L", Insulation: "PEVA lining", Dimensions: "40cm x 25cm x 30cm" },
  },
  {
    id: "oc-015",
    name: "Emergency Survival Kit",
    category: "outdoor-camping",
    price: 39.99,
    image: "/emergency-survival-kit-camping.jpg",
    rating: 4.8,
    reviews: 2109,
    inStock: true,
    description: "Comprehensive survival kit for emergencies.",
    features: ["40+ items", "First aid supplies", "Fire starter", "Compact case"],
    specifications: { Items: "40+", Weight: "1.1kg", Case: "Water-resistant" },
  },
  {
    id: "oc-016",
    name: "Solar Powered Charger",
    category: "outdoor-camping",
    price: 44.99,
    image: "/solar-powered-charger-camping.jpg",
    rating: 4.6,
    reviews: 1654,
    inStock: true,
    description: "Charge devices using solar power outdoors.",
    features: ["20W solar panel", "Dual USB ports", "Foldable design", "Weather-resistant"],
    specifications: { Power: "20W", Output: "5V/2.4A per port", Weight: "580g" },
  },
  {
    id: "oc-017",
    name: "Camping Cot Portable",
    category: "outdoor-camping",
    price: 64.99,
    originalPrice: 89.99,
    image: "/camping-cot-portable-folding.jpg",
    rating: 4.7,
    reviews: 876,
    inStock: true,
    description: "Elevated cot for comfortable camping sleep.",
    features: ["Aluminum frame", "Supports 150kg", "Folds flat", "Carry bag"],
    specifications: {
      Material: "Aluminum + Oxford fabric",
      Dimensions: "190cm x 65cm x 40cm",
      "Load Capacity": "150kg",
    },
  },
  {
    id: "oc-018",
    name: "Headlamp LED Rechargeable",
    category: "outdoor-camping",
    price: 22.99,
    image: "/headlamp-led-rechargeable-camping.jpg",
    rating: 4.8,
    reviews: 2345,
    inStock: true,
    description: "Hands-free lighting for night activities.",
    features: ["1200 lumens", "USB rechargeable", "5 light modes", "Waterproof IPX4"],
    specifications: { Brightness: "1200 lumens", "Battery Life": "4-30 hours", Weight: "95g" },
  },
  {
    id: "oc-019",
    name: "Camping Table Folding",
    category: "outdoor-camping",
    price: 37.99,
    image: "/camping-table-folding-portable.jpg",
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    description: "Lightweight table for outdoor dining.",
    features: ["Aluminum construction", "Folds compactly", "Adjustable legs", "Carry handle"],
    specifications: { Material: "Aluminum", Dimensions: "70cm x 50cm x 60cm", Weight: "2.8kg" },
  },
  {
    id: "oc-020",
    name: "Camping Shower Bag",
    category: "outdoor-camping",
    price: 16.99,
    image: "/camping-shower-bag-solar.jpg",
    rating: 4.5,
    reviews: 987,
    inStock: true,
    description: "Solar-heated shower for camping hygiene.",
    features: ["20L capacity", "Solar heating", "Temperature indicator", "Shower head included"],
    specifications: { Capacity: "20L", Material: "PVC", "Heating Time": "3 hours in sun" },
  },

  // Sports Equipment (20 products)
  {
    id: "se-001",
    name: "Premium Yoga Mat Non-Slip",
    category: "sports-equipment",
    price: 29.99,
    originalPrice: 44.99,
    image: "/premium-yoga-mat-non-slip.jpg",
    rating: 4.8,
    reviews: 4567,
    inStock: true,
    description: "High-quality yoga mat with excellent grip and cushioning.",
    features: ["6mm thickness", "Non-slip surface", "Eco-friendly TPE", "Carrying strap included"],
    specifications: { Material: "TPE", Thickness: "6mm", Dimensions: "183cm x 61cm" },
  },
  {
    id: "se-002",
    name: "Speed Jump Rope with Counter",
    category: "sports-equipment",
    price: 12.99,
    image: "/speed-jump-rope-with-counter.jpg",
    rating: 4.6,
    reviews: 2341,
    inStock: true,
    description: "Professional jump rope with digital counter.",
    features: ["Digital counter", "Adjustable length", "Ball bearings", "Comfortable grips"],
    specifications: { Material: "Steel wire + PVC coating", Length: "Adjustable up to 3m", Weight: "180g" },
  },
  {
    id: "se-003",
    name: "Resistance Bands Set of 5",
    category: "sports-equipment",
    price: 19.99,
    image: "/resistance-bands-set-of-5.jpg",
    rating: 4.7,
    reviews: 3210,
    inStock: true,
    description: "Complete set of resistance bands for strength training.",
    features: ["5 resistance levels", "Natural latex", "Carry bag", "Exercise guide"],
    specifications: { Material: "Natural Latex", Resistance: "5-35 lbs", Dimensions: "30cm circumference" },
  },
  {
    id: "se-004",
    name: "Adjustable Dumbbells Pair",
    category: "sports-equipment",
    price: 89.99,
    originalPrice: 129.99,
    image: "/adjustable-dumbbells-pair.jpg",
    rating: 4.8,
    reviews: 1876,
    inStock: true,
    description: "Space-saving adjustable dumbbells for home workouts.",
    features: ["Adjustable 5-25 lbs", "Quick-change system", "Compact design", "Non-slip handles"],
    specifications: { "Weight Range": "5-25 lbs per dumbbell", Increments: "5 lbs", Material: "Steel + Rubber" },
  },
  {
    id: "se-005",
    name: "Folding Treadmill Electric",
    category: "sports-equipment",
    price: 399.99,
    originalPrice: 599.99,
    image: "/folding-treadmill-electric.jpg",
    rating: 4.6,
    reviews: 987,
    inStock: true,
    description: "Compact treadmill perfect for home use.",
    features: ["Foldable design", "LCD display", "12 programs", "Max speed 12 km/h"],
    specifications: { "Motor Power": "2.5 HP", "Running Surface": "120cm x 40cm", "Max Weight": "120kg" },
  },
  {
    id: "se-006",
    name: "Wrist Support Wraps Pair",
    category: "sports-equipment",
    price: 14.99,
    image: "/wrist-support-wraps-pair.jpg",
    rating: 4.7,
    reviews: 1654,
    inStock: true,
    description: "Professional wrist wraps for weightlifting.",
    features: ["18-inch length", "Thumb loop", "Adjustable tightness", "Breathable fabric"],
    specifications: { Length: "18 inches", Material: "Cotton + Elastic", Closure: "Velcro" },
  },
  {
    id: "se-007",
    name: "Ab Roller Wheel",
    category: "sports-equipment",
    price: 16.99,
    image: "/ab-roller-wheel-exercise.jpg",
    rating: 4.5,
    reviews: 2109,
    inStock: true,
    description: "Effective ab roller for core strengthening.",
    features: ["Dual wheels", "Non-slip handles", "Knee pad included", "Stable design"],
    specifications: { Material: "ABS + TPR", "Wheel Diameter": "18cm", "Max Load": "150kg" },
  },
  {
    id: "se-008",
    name: "Exercise Ball with Pump",
    category: "sports-equipment",
    price: 18.99,
    image: "/exercise-ball-with-pump.jpg",
    rating: 4.6,
    reviews: 1432,
    inStock: true,
    description: "Versatile exercise ball for fitness and yoga.",
    features: ["Anti-burst design", "Multiple sizes", "Pump included", "Textured surface"],
    specifications: { Material: "PVC", Sizes: "55cm, 65cm, 75cm", "Max Load": "300kg" },
  },
  {
    id: "se-009",
    name: "Foam Roller for Muscle Recovery",
    category: "sports-equipment",
    price: 21.99,
    image: "/foam-roller-muscle-recovery.jpg",
    rating: 4.7,
    reviews: 2345,
    inStock: true,
    description: "High-density foam roller for muscle recovery.",
    features: ["High-density foam", "Textured surface", "Multiple sizes", "Carry bag"],
    specifications: { Material: "EVA Foam", Dimensions: "33cm x 14cm", Density: "High" },
  },
  {
    id: "se-010",
    name: "Kettlebell Cast Iron",
    category: "sports-equipment",
    price: 34.99,
    image: "/kettlebell-cast-iron.jpg",
    rating: 4.8,
    reviews: 1234,
    inStock: true,
    description: "Durable cast iron kettlebell for strength training.",
    features: ["Cast iron construction", "Wide handle", "Flat base", "Multiple weights"],
    specifications: { Material: "Cast Iron", Weights: "8kg, 12kg, 16kg, 20kg", Finish: "Powder coated" },
  },
  {
    id: "se-011",
    name: "Pull-Up Bar Doorway",
    category: "sports-equipment",
    price: 27.99,
    image: "/pull-up-bar-doorway.jpg",
    rating: 4.6,
    reviews: 1765,
    inStock: true,
    description: "Easy-install pull-up bar for doorways.",
    features: ["No screws needed", "Multiple grip positions", "Supports 150kg", "Foam grips"],
    specifications: { Material: "Steel", "Adjustable Width": "62-100cm", "Max Load": "150kg" },
  },
  {
    id: "se-012",
    name: "Ankle Weights Pair",
    category: "sports-equipment",
    price: 22.99,
    image: "/ankle-weights-pair.jpg",
    rating: 4.5,
    reviews: 987,
    inStock: true,
    description: "Adjustable ankle weights for resistance training.",
    features: ["Adjustable weight", "Comfortable padding", "Secure straps", "Pair included"],
    specifications: { "Weight Range": "1-5 lbs per ankle", Material: "Neoprene + Iron sand", Closure: "Velcro" },
  },
  {
    id: "se-013",
    name: "Yoga Block Set of 2",
    category: "sports-equipment",
    price: 15.99,
    image: "/yoga-block-set-of-2.jpg",
    rating: 4.7,
    reviews: 1543,
    inStock: true,
    description: "Supportive yoga blocks for better alignment.",
    features: ["High-density foam", "Non-slip surface", "Set of 2", "Multiple colors"],
    specifications: { Material: "EVA Foam", Dimensions: "23cm x 15cm x 10cm", Weight: "150g each" },
  },
  {
    id: "se-014",
    name: "Suspension Training Straps",
    category: "sports-equipment",
    price: 39.99,
    image: "/suspension-training-straps.jpg",
    rating: 4.8,
    reviews: 1876,
    inStock: true,
    description: "Versatile suspension trainer for full-body workouts.",
    features: ["Adjustable length", "Door anchor included", "Handles and foot cradles", "Carry bag"],
    specifications: { Material: "Nylon webbing", "Max Load": "180kg", "Length Range": "Adjustable" },
  },
  {
    id: "se-015",
    name: "Medicine Ball",
    category: "sports-equipment",
    price: 28.99,
    image: "/medicine-ball-weighted.jpg",
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    description: "Weighted medicine ball for strength and conditioning.",
    features: ["Textured surface", "Durable rubber", "Multiple weights", "Easy to grip"],
    specifications: { Material: "Rubber", Weights: "4kg, 6kg, 8kg, 10kg", Diameter: "22-28cm" },
  },
  {
    id: "se-016",
    name: "Agility Ladder",
    category: "sports-equipment",
    price: 17.99,
    image: "/agility-ladder-training.jpg",
    rating: 4.5,
    reviews: 1432,
    inStock: true,
    description: "Improve speed and agility with this training ladder.",
    features: ["12 adjustable rungs", "Carry bag", "Ground stakes", "Durable nylon"],
    specifications: { Length: "6 meters", Rungs: "12", Material: "Nylon + Plastic" },
  },
  {
    id: "se-017",
    name: "Push-Up Bars",
    category: "sports-equipment",
    price: 19.99,
    image: "/push-up-bars-exercise.jpg",
    rating: 4.7,
    reviews: 1654,
    inStock: true,
    description: "Ergonomic push-up bars for better form.",
    features: ["Foam grips", "Non-slip base", "Supports 150kg", "Compact design"],
    specifications: { Material: "Steel + Foam", Dimensions: "23cm x 15cm", "Max Load": "150kg" },
  },
  {
    id: "se-018",
    name: "Weighted Jump Rope",
    category: "sports-equipment",
    price: 24.99,
    image: "/weighted-jump-rope.jpg",
    rating: 4.6,
    reviews: 987,
    inStock: true,
    description: "Heavy jump rope for intense cardio workouts.",
    features: ["Weighted handles", "Adjustable length", "Ball bearings", "Durable cable"],
    specifications: { "Handle Weight": "0.5 lbs each", Material: "Steel cable + PVC", Length: "Adjustable" },
  },
  {
    id: "se-019",
    name: "Balance Board",
    category: "sports-equipment",
    price: 32.99,
    image: "/balance-board-training.jpg",
    rating: 4.7,
    reviews: 1234,
    inStock: true,
    description: "Improve balance and core strength.",
    features: ["Non-slip surface", "Wooden construction", "Multiple difficulty levels", "Supports 150kg"],
    specifications: { Material: "Wood + Cork", Diameter: "40cm", "Max Load": "150kg" },
  },
  {
    id: "se-020",
    name: "Resistance Tubes with Handles",
    category: "sports-equipment",
    price: 26.99,
    image: "/resistance-tubes-with-handles.jpg",
    rating: 4.8,
    reviews: 2109,
    inStock: true,
    description: "Versatile resistance tubes for full-body training.",
    features: ["5 tubes included", "Comfortable handles", "Door anchor", "Ankle straps"],
    specifications: {
      Material: "Latex tubes",
      Resistance: "Up to 150 lbs combined",
      Includes: "Handles, anchor, straps",
    },
  },

  // Pu-er Tea (20 products)
  {
    id: "pt-001",
    name: "Aged Pu-er Tea Cake 357g",
    category: "puer-tea",
    price: 49.99,
    originalPrice: 69.99,
    image: "/aged-puer-tea-cake-357g.jpg",
    rating: 4.9,
    reviews: 876,
    inStock: true,
    description: "Premium aged Pu-er tea cake from Yunnan.",
    features: ["10-year aged", "Yunnan origin", "Rich flavor", "Traditional pressing"],
    specifications: { Weight: "357g", Origin: "Yunnan, China", Age: "10 years", Type: "Ripe Pu-er" },
  },
  {
    id: "pt-002",
    name: "Ancient Tree Pu-er Tea",
    category: "puer-tea",
    price: 89.99,
    originalPrice: 129.99,
    image: "/ancient-tree-puer-tea.jpg",
    rating: 4.8,
    reviews: 543,
    inStock: true,
    description: "Rare tea from 300-year-old tea trees.",
    features: ["Ancient tree source", "Complex flavor", "Limited production", "Gift packaging"],
    specifications: { Weight: "200g", Origin: "Yunnan ancient tea forest", Age: "Raw Pu-er", "Tree Age": "300+ years" },
  },
  {
    id: "pt-003",
    name: "Mini Pu-er Tea Tuocha Set",
    category: "puer-tea",
    price: 24.99,
    image: "/mini-puer-tea-tuocha-set.jpg",
    rating: 4.7,
    reviews: 1234,
    inStock: true,
    description: "Convenient single-serving Pu-er tea portions.",
    features: ["10 pieces per set", "Individual wrapping", "Perfect for travel", "Consistent quality"],
    specifications: { Weight: "5g per piece", Quantity: "10 pieces", Type: "Ripe Pu-er", Packaging: "Individual wrap" },
  },
  {
    id: "pt-004",
    name: "Pu-er Tea Brick 250g",
    category: "puer-tea",
    price: 34.99,
    image: "/puer-tea-brick-250g.jpg",
    rating: 4.6,
    reviews: 765,
    inStock: true,
    description: "Traditional brick-pressed Pu-er tea.",
    features: ["Brick format", "Easy to store", "Smooth taste", "5-year aged"],
    specifications: { Weight: "250g", Format: "Brick", Age: "5 years", Type: "Ripe Pu-er" },
  },
  {
    id: "pt-005",
    name: "Commemorative Pu-er Tea Cake",
    category: "puer-tea",
    price: 79.99,
    image: "/commemorative-puer-tea-cake.jpg",
    rating: 4.8,
    reviews: 432,
    inStock: true,
    description: "Special edition commemorative tea cake.",
    features: ["Limited edition", "Collectible packaging", "Premium quality", "Certificate included"],
    specifications: { Weight: "357g", Edition: "Limited", Age: "8 years", Type: "Raw Pu-er" },
  },
  {
    id: "pt-006",
    name: "Pu-er Tea Gift Box Set",
    category: "puer-tea",
    price: 129.99,
    originalPrice: 179.99,
    image: "/puer-tea-gift-box-set.jpg",
    rating: 4.9,
    reviews: 321,
    inStock: true,
    description: "Luxury gift set with assorted Pu-er teas.",
    features: ["5 varieties included", "Elegant gift box", "Tea tools included", "Perfect for gifting"],
    specifications: {
      "Total Weight": "500g",
      Varieties: "5 types",
      Includes: "Tea knife, storage bag",
      Packaging: "Luxury box",
    },
  },
  {
    id: "pt-007",
    name: "Organic Pu-er Tea Loose Leaf",
    category: "puer-tea",
    price: 29.99,
    image: "/organic-puer-tea-loose-leaf.jpg",
    rating: 4.7,
    reviews: 987,
    inStock: true,
    description: "Certified organic loose leaf Pu-er tea.",
    features: ["Organic certified", "Loose leaf format", "Easy to brew", "Resealable bag"],
    specifications: { Weight: "200g", Certification: "Organic", Type: "Ripe Pu-er", Format: "Loose leaf" },
  },
  {
    id: "pt-008",
    name: "Pu-er Tea Sampler Set",
    category: "puer-tea",
    price: 39.99,
    image: "/puer-tea-sampler-set.jpg",
    rating: 4.6,
    reviews: 654,
    inStock: true,
    description: "Discover different Pu-er tea varieties.",
    features: ["8 varieties", "Tasting notes included", "Sample sizes", "Great for beginners"],
    specifications: {
      Varieties: "8 types",
      "Sample Size": "10g each",
      "Total Weight": "80g",
      Includes: "Tasting guide",
    },
  },
  {
    id: "pt-009",
    name: "Premium Raw Pu-er Tea",
    category: "puer-tea",
    price: 64.99,
    image: "/premium-raw-puer-tea.jpg",
    rating: 4.8,
    reviews: 543,
    inStock: true,
    description: "High-quality raw Pu-er for aging.",
    features: ["Raw (Sheng) Pu-er", "Aging potential", "Complex flavor", "Mountain origin"],
    specifications: { Weight: "357g", Type: "Raw Pu-er", Origin: "Yunnan mountains", Age: "3 years" },
  },
  {
    id: "pt-010",
    name: "Pu-er Tea Mushroom Shape",
    category: "puer-tea",
    price: 19.99,
    image: "/puer-tea-mushroom-shape.jpg",
    rating: 4.5,
    reviews: 876,
    inStock: true,
    description: "Unique mushroom-shaped Pu-er tea.",
    features: ["Mushroom shape", "Single serving", "Decorative", "Smooth taste"],
    specifications: { Weight: "100g", Shape: "Mushroom (Tuocha)", Type: "Ripe Pu-er", Age: "3 years" },
  },
  {
    id: "pt-011",
    name: "Vintage Pu-er Tea 20 Years",
    category: "puer-tea",
    price: 199.99,
    originalPrice: 299.99,
    image: "/vintage-puer-tea-20-years.jpg",
    rating: 4.9,
    reviews: 234,
    inStock: true,
    description: "Exceptionally aged 20-year-old Pu-er.",
    features: ["20-year aged", "Rare vintage", "Smooth and mellow", "Collector's item"],
    specifications: { Weight: "357g", Age: "20 years", Type: "Ripe Pu-er", Storage: "Dry warehouse" },
  },
  {
    id: "pt-012",
    name: "Pu-er Tea with Chrysanthemum",
    category: "puer-tea",
    price: 27.99,
    image: "/puer-tea-with-chrysanthemum.jpg",
    rating: 4.6,
    reviews: 765,
    inStock: true,
    description: "Pu-er tea blended with chrysanthemum flowers.",
    features: ["Floral blend", "Soothing taste", "Health benefits", "Natural ingredients"],
    specifications: { Weight: "150g", Blend: "Pu-er + Chrysanthemum", Type: "Ripe Pu-er", Format: "Loose blend" },
  },
  {
    id: "pt-013",
    name: "Pu-er Tea Dragon Ball",
    category: "puer-tea",
    price: 34.99,
    image: "/puer-tea-dragon-ball.jpg",
    rating: 4.7,
    reviews: 543,
    inStock: true,
    description: "Hand-rolled Pu-er tea balls.",
    features: ["Hand-rolled", "Single serving", "Premium leaves", "Set of 12"],
    specifications: { Weight: "8g per ball", Quantity: "12 balls", Type: "Raw Pu-er", Crafting: "Hand-rolled" },
  },
  {
    id: "pt-014",
    name: "Pu-er Tea Cake with Artwork",
    category: "puer-tea",
    price: 59.99,
    image: "/puer-tea-cake-with-artwork.jpg",
    rating: 4.8,
    reviews: 432,
    inStock: true,
    description: "Pu-er tea cake with beautiful artistic packaging.",
    features: ["Artistic design", "Gift-worthy", "Premium quality", "Display-ready"],
    specifications: { Weight: "357g", Type: "Ripe Pu-er", Age: "7 years", Packaging: "Artistic wrapper" },
  },
  {
    id: "pt-015",
    name: "Pu-er Tea Nuggets",
    category: "puer-tea",
    price: 22.99,
    image: "/puer-tea-nuggets.jpg",
    rating: 4.5,
    reviews: 654,
    inStock: true,
    description: "Convenient Pu-er tea nuggets for easy brewing.",
    features: ["Pre-broken pieces", "Easy to brew", "Consistent quality", "Resealable bag"],
    specifications: { Weight: "200g", Format: "Nuggets", Type: "Ripe Pu-er", Age: "5 years" },
  },
  {
    id: "pt-016",
    name: "Palace Grade Pu-er Tea",
    category: "puer-tea",
    price: 149.99,
    image: "/palace-grade-puer-tea.jpg",
    rating: 4.9,
    reviews: 187,
    inStock: true,
    description: "Highest grade Pu-er tea, palace quality.",
    features: ["Palace grade", "Golden buds", "Exceptional quality", "Limited availability"],
    specifications: { Weight: "200g", Grade: "Palace (Gong Ting)", Type: "Ripe Pu-er", Age: "12 years" },
  },
  {
    id: "pt-017",
    name: "Pu-er Tea Brick Vintage",
    category: "puer-tea",
    price: 44.99,
    image: "/puer-tea-brick-vintage.jpg",
    rating: 4.7,
    reviews: 543,
    inStock: true,
    description: "Vintage brick-pressed Pu-er tea.",
    features: ["Vintage pressing", "Well-aged", "Rich flavor", "Collectible"],
    specifications: { Weight: "250g", Format: "Brick", Age: "15 years", Type: "Ripe Pu-er" },
  },
  {
    id: "pt-018",
    name: "Pu-er Tea Blend Assortment",
    category: "puer-tea",
    price: 54.99,
    image: "/puer-tea-blend-assortment.jpg",
    rating: 4.6,
    reviews: 432,
    inStock: true,
    description: "Assorted Pu-er tea blends in one package.",
    features: ["6 blends", "Variety pack", "Different flavors", "Gift box"],
    specifications: { Varieties: "6 blends", "Total Weight": "300g", Format: "Mixed", Packaging: "Gift box" },
  },
  {
    id: "pt-019",
    name: "Pu-er Tea Mini Cake Set",
    category: "puer-tea",
    price: 39.99,
    image: "/pu-er-tea-mini-cake-set.jpg",
    rating: 4.7,
    reviews: 765,
    inStock: true,
    description: "Set of mini Pu-er tea cakes.",
    features: ["5 mini cakes", "Perfect portions", "Easy storage", "Variety of ages"],
    specifications: { Weight: "50g per cake", Quantity: "5 cakes", Type: "Mixed (Raw & Ripe)", Ages: "Various" },
  },
  {
    id: "pt-020",
    name: "Pu-er Tea Decorative Display",
    category: "puer-tea",
    price: 69.99,
    image: "/pu-er-tea-decorative-display.jpg",
    rating: 4.8,
    reviews: 321,
    inStock: true,
    description: "Ornamental Pu-er tea for display and drinking.",
    features: ["Decorative design", "Display stand included", "Premium quality", "Conversation piece"],
    specifications: { Weight: "357g", Type: "Ripe Pu-er", Age: "10 years", Includes: "Display stand" },
  },

  // Jade & Jewelry (20 products)
  {
    id: "jj-001",
    name: "Natural Jade Bracelet",
    category: "jade-jewelry",
    price: 79.99,
    originalPrice: 109.99,
    image: "/natural-jade-bracelet-smooth.jpg",
    rating: 4.8,
    reviews: 1234,
    inStock: true,
    description: "Elegant bracelet made from genuine jade.",
    features: ["100% natural jade", "Smooth polished finish", "Comfortable fit", "Gift box included"],
    specifications: { Material: "Jade", Diameter: "60mm", "Bead Size": "10mm", Color: "Green" },
  },
  {
    id: "jj-002",
    name: "Sterling Silver Jade Pendant",
    category: "jade-jewelry",
    price: 59.99,
    image: "/sterling-silver-jade-pendant-carved.jpg",
    rating: 4.7,
    reviews: 876,
    inStock: true,
    description: "Beautiful pendant featuring carved jade and sterling silver.",
    features: ["Sterling silver setting", "Intricate carving", "Includes 18-inch chain", "Hypoallergenic"],
    specifications: {
      Material: "Jade, Sterling Silver",
      "Pendant Size": "30x20mm",
      "Chain Length": "18 inches",
      Style: "Carved",
    },
  },
  {
    id: "jj-003",
    name: "Jade Drop Earrings",
    category: "jade-jewelry",
    price: 44.99,
    image: "/jade-drop-earrings-silver.jpg",
    rating: 4.6,
    reviews: 654,
    inStock: true,
    description: "Delicate jade drop earrings for everyday elegance.",
    features: ["Genuine jade stones", "Sterling silver hooks", "Lightweight", "Comfortable to wear"],
    specifications: { Material: "Jade, Sterling Silver", Length: "40mm", Style: "Drop earrings" },
  },
  {
    id: "jj-004",
    name: "Jade Ring Adjustable",
    category: "jade-jewelry",
    price: 39.99,
    image: "/jade-ring-adjustable-silver-band.jpg",
    rating: 4.5,
    reviews: 543,
    inStock: true,
    description: "Stylish adjustable ring with a jade accent.",
    features: ["Adjustable silver band", "Natural jade stone", "Minimalist design", "Comfortable fit"],
    specifications: { Material: "Jade, Sterling Silver", Size: "Adjustable", "Stone Size": "8mm round" },
  },
  {
    id: "jj-005",
    name: "Set of 3 Jade Bangles",
    category: "jade-jewelry",
    price: 99.99,
    originalPrice: 149.99,
    image: "/set-of-3-jade-bangles-smooth.jpg",
    rating: 4.9,
    reviews: 432,
    inStock: true,
    description: "Chic set of three smooth jade bangles.",
    features: ["Natural jade", "Set of 3", "Smooth finish", "Stackable design"],
    specifications: { Material: "Jade", Diameter: "65mm", Quantity: "3 pieces", Finish: "Polished" },
  },
  {
    id: "jj-006",
    name: "Jade Necklace with Pendant",
    category: "jade-jewelry",
    price: 84.99,
    image: "/jade-necklace-pendant-silver-chain.jpg",
    rating: 4.7,
    reviews: 765,
    inStock: true,
    description: "Sophisticated jade necklace with a detailed pendant.",
    features: ["Natural jade pendant", "Sterling silver chain", "Elegant design", "Adjustable length"],
    specifications: { Material: "Jade, Sterling Silver", "Pendant Size": "40x25mm", "Chain Length": "16-18 inches" },
  },
  {
    id: "jj-007",
    name: "Carved Jade Cufflinks",
    category: "jade-jewelry",
    price: 69.99,
    image: "/carved-jade-cufflinks-silver.jpg",
    rating: 4.6,
    reviews: 321,
    inStock: true,
    description: "Exquisite cufflinks made from carved jade.",
    features: ["Genuine carved jade", "Sterling silver fittings", "Classic design", "Gift box"],
    specifications: { Material: "Jade, Sterling Silver", Size: "18x14mm", Style: "Carved" },
  },
  {
    id: "jj-008",
    name: "Jade Bead Stretch Bracelet",
    category: "jade-jewelry",
    price: 29.99,
    image: "/jade-bead-stretch-bracelet-matte.jpg",
    rating: 4.5,
    reviews: 987,
    inStock: true,
    description: "Simple and stylish stretch bracelet with jade beads.",
    features: ["Natural jade beads", "Stretch cord", "Easy to wear", "Matte finish"],
    specifications: { Material: "Jade", "Bead Size": "8mm", Length: "Stretch fit" },
  },
  {
    id: "jj-009",
    name: "Jade Brooch Flower Design",
    category: "jade-jewelry",
    price: 54.99,
    image: "/jade-brooch-flower-design-silver.jpg",
    rating: 4.8,
    reviews: 432,
    inStock: true,
    description: "Beautiful floral-design brooch adorned with jade.",
    features: ["Intricate floral design", "Natural jade accents", "Silver tone", "Secure clasp"],
    specifications: { Material: "Metal Alloy, Jade", Size: "50x40mm", Style: "Brooch" },
  },
  {
    id: "jj-010",
    name: "Jade Hair Pins Set",
    category: "jade-jewelry",
    price: 34.99,
    image: "/jade-hair-pins-set-silver.jpg",
    rating: 4.7,
    reviews: 765,
    inStock: true,
    description: "Set of decorative hair pins with jade embellishments.",
    features: ["Jade embellishments", "Silver tone pins", "Set of 4", "Adds elegance"],
    specifications: { Material: "Metal Alloy, Jade", Length: "70mm", Quantity: "4 pieces" },
  },
  {
    id: "jj-011",
    name: "Jade Tie Clip",
    category: "jade-jewelry",
    price: 49.99,
    image: "/jade-tie-clip-silver.jpg",
    rating: 4.6,
    reviews: 321,
    inStock: true,
    description: "Sophisticated tie clip featuring a jade inlay.",
    features: ["Jade inlay", "Sterling silver clip", "Polished finish", "Giftable"],
    specifications: { Material: "Jade, Sterling Silver", Size: "55x6mm", Style: "Tie clip" },
  },
  {
    id: "jj-012",
    name: "Jade Charm Bracelet",
    category: "jade-jewelry",
    price: 74.99,
    image: "/jade-charm-bracelet-silver.jpg",
    rating: 4.8,
    reviews: 543,
    inStock: true,
    description: "Charming bracelet with various jade charms.",
    features: ["Assorted jade charms", "Sterling silver chain", "Adjustable length", "Unique design"],
    specifications: { Material: "Jade, Sterling Silver", Length: "7-8 inches", Charms: "Various jade pieces" },
  },
  {
    id: "jj-013",
    name: "Jade Buddha Pendant",
    category: "jade-jewelry",
    price: 119.99,
    image: "/jade-buddha-pendant-carved.jpg",
    rating: 4.9,
    reviews: 234,
    inStock: true,
    description: "Serene pendant featuring a carved jade Buddha.",
    features: ["Carved jade Buddha", "Exquisite detail", "Symbol of peace", "Includes chain"],
    specifications: { Material: "Jade", "Pendant Size": "45x30mm", Style: "Carved Buddha" },
  },
  {
    id: "jj-014",
    name: "Jade Bead Necklace",
    category: "jade-jewelry",
    price: 139.99,
    originalPrice: 189.99,
    image: "/jade-bead-necklace-long.jpg",
    rating: 4.8,
    reviews: 654,
    inStock: true,
    description: "Classic necklace strung with smooth jade beads.",
    features: ["Genuine jade beads", "Long length", "Timeless style", "Silk cord"],
    specifications: { Material: "Jade", "Bead Size": "10mm", Length: "36 inches", Cord: "Silk" },
  },
  {
    id: "jj-015",
    name: "Jade Inlay Watch Band",
    category: "jade-jewelry",
    price: 99.99,
    image: "/jade-inlay-watch-band-silver.jpg",
    rating: 4.7,
    reviews: 432,
    inStock: true,
    description: "Luxurious watch band with jade inlay.",
    features: ["Jade inlay details", "Sterling silver components", "Elegant and unique", "Standard lug width"],
    specifications: { Material: "Jade, Sterling Silver", Width: "20mm", Style: "Watch band" },
  },
  {
    id: "jj-016",
    name: "Jade Pixiu Bracelet",
    category: "jade-jewelry",
    price: 89.99,
    image: "/jade-pixiu-bracelet-feng-shui.jpg",
    rating: 4.9,
    reviews: 321,
    inStock: true,
    description: "Feng Shui bracelet with a jade Pixiu charm.",
    features: ["Jade Pixiu charm", "Amethyst beads", "Stretch fit", "Good fortune symbol"],
    specifications: { Material: "Jade, Amethyst", Size: "Stretch fit", Charm: "Pixiu" },
  },
  {
    id: "jj-017",
    name: "Jade Inlay Brooch",
    category: "jade-jewelry",
    price: 64.99,
    image: "/jade-inlay-brooch-ornate.jpg",
    rating: 4.6,
    reviews: 543,
    inStock: true,
    description: "Ornate brooch with intricate jade inlay.",
    features: ["Detailed jade inlay", "Antique gold tone", "Secure clasp", "Elegant statement piece"],
    specifications: { Material: "Metal Alloy, Jade", Size: "60x45mm", Style: "Brooch" },
  },
  {
    id: "jj-018",
    name: "Jade Bead Anklet",
    category: "jade-jewelry",
    price: 24.99,
    image: "/jade-bead-anklet-silver-chain.jpg",
    rating: 4.5,
    reviews: 765,
    inStock: true,
    description: "Delicate anklet with small jade beads.",
    features: ["Small jade beads", "Sterling silver chain", "Adjustable length", "Lightweight"],
    specifications: { Material: "Jade, Sterling Silver", Length: "9-10 inches", "Bead Size": "4mm" },
  },
  {
    id: "jj-019",
    name: "Jade & Pearl Necklace",
    category: "jade-jewelry",
    price: 109.99,
    image: "/jade-pearl-necklace-classic.jpg",
    rating: 4.8,
    reviews: 432,
    inStock: true,
    description: "Classic necklace combining jade and pearls.",
    features: ["Freshwater pearls", "Jade beads", "Sterling silver clasp", "Timeless design"],
    specifications: { Material: "Jade, Pearls, Sterling Silver", Length: "18 inches" },
  },
  {
    id: "jj-020",
    name: "Jade Fan Earrings",
    category: "jade-jewelry",
    price: 49.99,
    image: "/jade-fan-earrings-silver.jpg",
    rating: 4.7,
    reviews: 321,
    inStock: true,
    description: "Unique fan-shaped earrings with jade accents.",
    features: ["Fan shape", "Jade accents", "Sterling silver hooks", "Lightweight"],
    specifications: { Material: "Metal Alloy, Jade, Sterling Silver", Length: "50mm", Style: "Dangle earrings" },
  },

  // Purple Clay Teapots (20 products)
  {
    id: "tp-001",
    name: "Yixing Zisha Teapot",
    category: "teapots",
    price: 129.99,
    originalPrice: 179.99,
    image: "/yixing-zisha-teapot-traditional.jpg",
    rating: 4.9,
    reviews: 876,
    inStock: true,
    description: "Authentic Yixing Zisha clay teapot for tea connoisseurs.",
    features: ["Handmade Zisha clay", "Enhances tea flavor", "Traditional design", "Includes infuser"],
    specifications: { Material: "Zisha Clay", Capacity: "250ml", Style: "Teapot" },
  },
  {
    id: "tp-002",
    name: "Purple Clay Gong Dao Bei",
    category: "teapots",
    price: 49.99,
    image: "/purple-clay-gong-dao-bei-fairness-cup.jpg",
    rating: 4.8,
    reviews: 543,
    inStock: true,
    description: "Purple clay fairness cup for serving tea.",
    features: ["Zisha clay material", "Even tea distribution", "Elegant design", "Durable"],
    specifications: { Material: "Purple Clay", Capacity: "200ml", Style: "Fairness cup" },
  },
  {
    id: "tp-003",
    name: "Miniature Teapot Set",
    category: "teapots",
    price: 69.99,
    image: "/miniature-teapot-set-purple-clay.jpg",
    rating: 4.7,
    reviews: 1234,
    inStock: true,
    description: "Charming miniature teapot set for display or small servings.",
    features: ["Set includes teapot and cups", "Handcrafted purple clay", "Decorative piece", "Unique gift"],
    specifications: { Material: "Purple Clay", Style: "Miniature tea set" },
  },
  {
    id: "tp-004",
    name: "Vintage Zisha Tea Urn",
    category: "teapots",
    price: 189.99,
    originalPrice: 249.99,
    image: "/vintage-zisha-tea-urn-storage.jpg",
    rating: 4.9,
    reviews: 432,
    inStock: true,
    description: "Aged Zisha clay tea urn for storing and aging tea.",
    features: ["Aged Zisha clay", "Airtight seal", "Preserves tea aroma", "Collector's item"],
    specifications: { Material: "Zisha Clay", Capacity: "1000ml", Style: "Tea urn" },
  },
  {
    id: "tp-005",
    name: "Purple Clay Tea Pet",
    category: "teapots",
    price: 24.99,
    image: "/purple-clay-tea-pet-buddha.jpg",
    rating: 4.6,
    reviews: 765,
    inStock: true,
    description: "Decorative purple clay tea pet.",
    features: ["Handmade Zisha clay", "Various shapes (Buddha shown)", "Enhances tea ceremony"],
    specifications: { Material: "Purple Clay", Style: "Tea pet" },
  },
  {
    id: "tp-006",
    name: "Hand-Painted Purple Clay Teapot",
    category: "teapots",
    price: 159.99,
    image: "/hand-painted-purple-clay-teapot-landscape.jpg",
    rating: 4.8,
    reviews: 321,
    inStock: true,
    description: "Exquisite teapot with hand-painted landscape scenes.",
    features: ["Painted Zisha clay", "Artistic design", "Smooth pouring spout", "Unique gift"],
    specifications: { Material: "Zisha Clay", Capacity: "300ml", Style: "Painted teapot" },
  },
  {
    id: "tp-007",
    name: "Zisha Tea Set (4-Piece)",
    category: "teapots",
    price: 229.99,
    image: "/zisha-tea-set-4-piece.jpg",
    rating: 4.9,
    reviews: 543,
    inStock: true,
    description: "Complete Zisha clay tea set for an authentic tea experience.",
    features: ["Includes teapot, fairness cup, 2 cups", "High-quality Zisha clay", "Elegant presentation"],
    specifications: { Material: "Zisha Clay", Pieces: "4", Style: "Tea set" },
  },
  {
    id: "tp-008",
    name: "Purple Clay Gaiwan",
    category: "teapots",
    price: 59.99,
    image: "/purple-clay-gaiwan-lid-cup.jpg",
    rating: 4.7,
    reviews: 987,
    inStock: true,
    description: "Versatile purple clay gaiwan for brewing tea.",
    features: ["Zisha clay construction", "Brew and drink from one vessel", "Easy to use", "Durable"],
    specifications: { Material: "Purple Clay", Capacity: "150ml", Style: "Gaiwan" },
  },
  {
    id: "tp-009",
    name: "Dragon-Shaped Zisha Teapot",
    category: "teapots",
    price: 199.99,
    image: "/dragon-shaped-zisha-teapot.jpg",
    rating: 4.8,
    reviews: 432,
    inStock: true,
    description: "Impressive teapot shaped like a dragon.",
    features: ["Intricate dragon carving", "Zisha clay", "Symbol of power", "Unique collectible"],
    specifications: { Material: "Zisha Clay", Capacity: "350ml", Style: "Sculptural teapot" },
  },
  {
    id: "tp-010",
    name: "Purple Clay Tea Caddy",
    category: "teapots",
    price: 79.99,
    image: "/purple-clay-tea-caddy-storage.jpg",
    rating: 4.6,
    reviews: 765,
    inStock: true,
    description: "Airtight purple clay container for storing tea leaves.",
    features: ["Zisha clay", "Airtight seal", "Preserves freshness", "Elegant storage"],
    specifications: { Material: "Purple Clay", Capacity: "150g tea", Style: "Tea caddy" },
  },
  {
    id: "tp-011",
    name: "Phoenix-Design Zisha Teapot",
    category: "teapots",
    price: 169.99,
    image: "/phoenix-design-zisha-teapot.jpg",
    rating: 4.9,
    reviews: 321,
    inStock: true,
    description: "Elegant teapot featuring a phoenix motif.",
    features: ["Zisha clay with phoenix design", "Symbol of good fortune", "Beautiful craftsmanship", "Gift ready"],
    specifications: { Material: "Zisha Clay", Capacity: "280ml", Style: "Artistic teapot" },
  },
  {
    id: "tp-012",
    name: "Purple Clay Tea Tray",
    category: "teapots",
    price: 89.99,
    image: "/purple-clay-tea-tray-drainage.jpg",
    rating: 4.7,
    reviews: 543,
    inStock: true,
    description: "Functional purple clay tea tray with drainage.",
    features: ["Zisha clay", "Water collection reservoir", "Durable and practical", "Enhances tea ceremony"],
    specifications: { Material: "Purple Clay", Dimensions: "30x20cm", Style: "Tea tray" },
  },
  {
    id: "tp-013",
    name: "Emperor-Style Zisha Teapot",
    category: "teapots",
    price: 249.99,
    originalPrice: 329.99,
    image: "/emperor-style-zisha-teapot-ornate.jpg",
    rating: 4.9,
    reviews: 234,
    inStock: true,
    description: "Ornate Zisha teapot inspired by imperial designs.",
    features: ["Intricate details", "High-quality Zisha clay", "Luxurious feel", "Collector's piece"],
    specifications: { Material: "Zisha Clay", Capacity: "400ml", Style: "Imperial teapot" },
  },
  {
    id: "tp-014",
    name: "Purple Clay Tea Cup Set",
    category: "teapots",
    price: 79.99,
    image: "/purple-clay-tea-cup-set-drinking.jpg",
    rating: 4.8,
    reviews: 654,
    inStock: true,
    description: "Set of four purple clay tea cups.",
    features: ["Handmade Zisha cups", "Comfortable to hold", "Set of 4", "Enhances tea aroma"],
    specifications: { Material: "Purple Clay", Quantity: "4 pieces", Style: "Tea cups" },
  },
  {
    id: "tp-015",
    name: "Zisha Infuser Tea Pot",
    category: "teapots",
    price: 99.99,
    image: "/zisha-infuser-tea-pot-modern.jpg",
    rating: 4.6,
    reviews: 432,
    inStock: true,
    description: "Modern Zisha clay teapot with built-in infuser.",
    features: ["Integrated infuser basket", "Zisha clay", "Easy to brew loose leaf", "Sleek design"],
    specifications: { Material: "Zisha Clay", Capacity: "200ml", Style: "Infuser teapot" },
  },
  {
    id: "tp-016",
    name: "Purple Clay Tea Boat",
    category: "teapots",
    price: 64.99,
    image: "/purple-clay-tea-boat-ceremony.jpg",
    rating: 4.7,
    reviews: 321,
    inStock: true,
    description: "Decorative purple clay 'tea boat' for tea ceremony.",
    features: ["Zisha clay crafting", "Symbolic piece", "Adds elegance", "For display"],
    specifications: { Material: "Purple Clay", Dimensions: "15x10cm", Style: "Tea ceremony accessory" },
  },
  {
    id: "tp-017",
    name: "Traditional Chinese Teapot Set",
    category: "teapots",
    price: 199.99,
    image: "/traditional-chinese-teapot-set-porcelain.jpg",
    rating: 4.8,
    reviews: 543,
    inStock: true,
    description: "Classic porcelain teapot set with traditional motifs.",
    features: ["Fine porcelain", "Includes teapot, cups, tray", "Intricate painting", "Gift packaging"],
    specifications: { Material: "Porcelain", Style: "Chinese tea set" },
  },
  {
    id: "tp-018",
    name: "Purple Clay Animal Teapot",
    category: "teapots",
    price: 149.99,
    image: "/purple-clay-animal-teapot-frog.jpg",
    rating: 4.6,
    reviews: 987,
    inStock: true,
    description: "Playful teapot shaped like an animal.",
    features: ["Zisha clay", "Animal design (frog shown)", "Whimsical and functional"],
    specifications: { Material: "Purple Clay", Capacity: "200ml", Style: "Animal teapot" },
  },
  {
    id: "tp-019",
    name: "Handmade Zisha Tea Ware Set",
    category: "teapots",
    price: 299.99,
    image: "/handmade-zisha-tea-ware-set-luxury.jpg",
    rating: 4.9,
    reviews: 432,
    inStock: true,
    description: "Luxury handmade Zisha tea ware set.",
    features: ["Complete tea set", "Premium Zisha clay", "Master craftsmanship", "Unparalleled quality"],
    specifications: { Material: "Zisha Clay", Style: "Luxury tea set" },
  },
  {
    id: "tp-020",
    name: "Purple Clay Tea Warmer",
    category: "teapots",
    price: 54.99,
    image: "/purple-clay-tea-warmer-candle.jpg",
    rating: 4.7,
    reviews: 765,
    inStock: true,
    description: "Purple clay tea warmer to keep tea hot.",
    features: ["Zisha clay construction", "Uses tea light candle", "Keeps pot warm", "Elegant design"],
    specifications: { Material: "Purple Clay", Style: "Tea warmer" },
  },
]

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId)
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.originalPrice).slice(0, 8)
}
